"""Graph Kernel public boundary (PR003+).

Runtime adapters and surfaces should import graph-memory operations from
``graph_memory.kernel`` only. Storage internals, preview loaders, and
latest-ingest selectors are not the legal production graph API.

Identity APIs (PR004) and contribution/merge APIs (PR005) are exported below.
Projection (PR007A) APIs are exported from ``graph_memory.kernel.world_projection``.
"""

from __future__ import annotations

from graph_memory.evidence.assertion_support import DurableAssertionSupport
from graph_memory.kernel.contribution_diagnostics import (
    build_contribution_integrity_report,
)
from graph_memory.kernel.contribution_merge import (
    contradict_edge_assertion_support,
    correct_edge_assertion_support,
    merge_contribution_to_revision,
    retract_graph_contribution,
    supersede_graph_contribution,
)
from apps.live_control_server.models.world_graph_contribution_models import (
    ContributionAssertionStatus,
    ContributionIdentityMention,
    ContributionIntegrityReport,
    ContributionMergeResult,
    ContributionSourceKind,
    ContributionStatus,
    GraphContribution,
    GraphContributionAssertion,
    GraphContributionAssertionCorrection,
)
from graph_memory.kernel.contribution_rebuild import rebuild_from_contributions
from apps.live_control_server.models.world_graph_contributions import (
    build_assertion,
    compute_assertion_id,
    compute_contribution_id,
    compute_contribution_payload_sha256,
    compute_contribution_source_payload_sha256,
    compute_correction_digest,
    create_edge_assertion_correction_contribution,
    create_edge_assertion_contradiction_contribution,
    create_graph_contribution,
)
from graph_memory.kernel.temporal import (
    TEMPORAL_ENVELOPE_SCHEMA,
    TemporalCertainty,
    TemporalEnvelopeV1,
    TemporalExtentV1,
    TemporalIntervalExtentV1,
    TemporalIntervalV1,
    TemporalPointExtentV1,
    TemporalPointKind,
    TemporalPointV1,
    TemporalRelation,
    TemporalScopeFormat,
    TemporalScopeInterpretationV1,
    TemporalScopeValidationError,
    interpret_temporal_scope,
    serialize_temporal_envelope,
    temporal_core_semantic_payload,
    temporal_source_payload,
)
from graph_memory.kernel.identity import (
    classify_identity_outcome,
    resolve_identity,
)
from graph_memory.kernel.identity_decisions import (
    build_identity_decision_record,
    compute_identity_decision_id,
    merge_identity,
    record_identity_decision,
    remove_identity_alias,
    split_identity,
    unmerge_identity,
)
from graph_memory.kernel.identity_models import (
    IdentityCandidate,
    IdentityCanonState,
    IdentityDecisionKind,
    IdentityDecisionRecord,
    IdentityAliasMapRewrite,
    IdentityMergeSideEffects,
    IdentityResolution,
    IdentityResolutionOutcome,
)
from graph_memory.kernel.identity_policy import (
    DEFAULT_IDENTITY_RESOLUTION_POLICY,
    IdentityResolutionPolicy,
)
from graph_memory.kernel.reviewed_world_initialization import (
    REVIEWED_PLAN_SCHEMA,
    REVIEWED_RECEIPT_SCHEMA,
    SESSIONLESS_FOCUS_SESSION_ID,
    ReviewedWorldInitializationAttestation,
    ReviewedWorldInitializationError,
    ReviewedWorldInitializationPlan,
    ReviewedWorldInitializationReceipt,
    ReviewedWorldInitializationResult,
    compute_reviewed_initialization_attestation_digest,
    compute_reviewed_initialization_plan_digest,
    initialize_reviewed_world,
    inspect_reviewed_world_initialization_state,
    read_reviewed_initialization_receipt,
)
from graph_memory.kernel.world_initialization import (
    build_empty_technical_baseline_store,
    compute_initialization_attestation_digest,
    compute_initialization_plan_digest,
    initialize_world_from_contributions,
    inspect_world_initialization_state,
    read_initialization_receipt,
)
from graph_memory.kernel.world_initialization_models import (
    WorldInitializationApprovalAttestation,
    WorldInitializationContribution,
    WorldInitializationError,
    WorldInitializationPlan,
    WorldInitializationReceipt,
    WorldInitializationResult,
)
from graph_memory.kernel.world_projection import (
    WorldGraphProjectionError,
    build_projection_payload,
    load_world_graph_revision_with_integrity,
    project_world_graph,
    project_world_graph_from_context,
    resolve_projection_admissibility,
    search_world_graph_projection,
    validate_projection_request_policy,
)
from graph_memory.kernel.world_read_runtime import (
    ProjectionReadContext,
    ProjectionRequestObservation,
    RequestIoCounters,
    ResidentRevision,
    begin_request_io,
    clear_world_read_runtime,
    get_last_projection_observation,
    get_request_io,
    get_world_read_runtime,
    reset_request_io,
    resolve_projection_read_context,
    set_last_projection_observation,
)
from graph_memory.kernel.world_retrieval import (
    AdmittedSourceAnchorMatch,
    WorldGraphRetrievalError,
    get_campaign_object,
    get_object_evidence,
    get_object_neighborhood,
    read_source_anchor,
    resolve_admitted_anchor_match,
    search_campaign_graph,
)
from graph_memory.kernel.world_graph import (
    WorldGraphError,
    WorldGraphHead,
    WorldGraphIntegrityError,
    WorldGraphIntegrityReport,
    WorldGraphNotFoundError,
    WorldGraphPublishResult,
    WorldGraphRevision,
    WorldGraphRevisionExistsError,
    WorldGraphStaleParentError,
    WorldGraphValidationError,
    build_world_graph_integrity_report,
    build_world_integrity_report,
    find_world_graph_revisions_by_operation_id,
    load_current_world_graph,
    load_world_graph_revision,
    load_world_graph_revision_manifest,
    open_current_world_graph,
    open_world_graph_head,
    publish_world_graph_revision,
    publish_world_revision,
    rollback_world_graph_head,
)
from graph_memory.kernel.world_revision_ready import (
    RevisionReadyConsumerLease,
    RevisionReadyMailbox,
    RevisionReadyOfferResult,
    WorldRevisionReadyNotification,
    allocate_revision_ready_commit_seq,
    clear_revision_ready_offer_observations,
    get_revision_ready_mailbox,
    get_revision_ready_offer_observations,
    notification_from_publish_result,
    offer_revision_ready,
    offer_revision_ready_from_publish,
    pop_revision_ready_queue_wait_ms,
    reset_revision_ready_mailbox,
)

__all__ = [
    # World graph (PR002/PR003)
    "WorldGraphError",
    "WorldGraphHead",
    "WorldGraphIntegrityError",
    "WorldGraphIntegrityReport",
    "WorldGraphNotFoundError",
    "WorldGraphPublishResult",
    "WorldGraphRevision",
    "WorldGraphRevisionExistsError",
    "WorldGraphStaleParentError",
    "WorldGraphValidationError",
    "build_world_graph_integrity_report",
    "build_world_integrity_report",
    "find_world_graph_revisions_by_operation_id",
    "load_current_world_graph",
    "load_world_graph_revision",
    "load_world_graph_revision_manifest",
    "open_current_world_graph",
    "open_world_graph_head",
    "publish_world_graph_revision",
    "publish_world_revision",
    "rollback_world_graph_head",
    # Revision-ready notification (OPT02)
    "RevisionReadyConsumerLease",
    "RevisionReadyMailbox",
    "RevisionReadyOfferResult",
    "WorldRevisionReadyNotification",
    "allocate_revision_ready_commit_seq",
    "clear_revision_ready_offer_observations",
    "get_revision_ready_mailbox",
    "get_revision_ready_offer_observations",
    "notification_from_publish_result",
    "offer_revision_ready",
    "offer_revision_ready_from_publish",
    "pop_revision_ready_queue_wait_ms",
    "reset_revision_ready_mailbox",
    # World initialization (PR006D1)
    "WorldInitializationApprovalAttestation",
    "WorldInitializationContribution",
    "WorldInitializationError",
    "WorldInitializationPlan",
    "WorldInitializationReceipt",
    "WorldInitializationResult",
    "build_empty_technical_baseline_store",
    "compute_contribution_payload_sha256",
    "compute_contribution_source_payload_sha256",
    "compute_initialization_attestation_digest",
    "compute_initialization_plan_digest",
    "initialize_world_from_contributions",
    "inspect_world_initialization_state",
    "read_initialization_receipt",
    # Reviewed-source world initialization (CR02A)
    "REVIEWED_PLAN_SCHEMA",
    "REVIEWED_RECEIPT_SCHEMA",
    "SESSIONLESS_FOCUS_SESSION_ID",
    "ReviewedWorldInitializationAttestation",
    "ReviewedWorldInitializationError",
    "ReviewedWorldInitializationPlan",
    "ReviewedWorldInitializationReceipt",
    "ReviewedWorldInitializationResult",
    "compute_reviewed_initialization_attestation_digest",
    "compute_reviewed_initialization_plan_digest",
    "initialize_reviewed_world",
    "inspect_reviewed_world_initialization_state",
    "read_reviewed_initialization_receipt",
    # Identity (PR004)
    "IdentityCandidate",
    "IdentityCanonState",
    "IdentityDecisionKind",
    "IdentityDecisionRecord",
    "IdentityAliasMapRewrite",
    "IdentityMergeSideEffects",
    "IdentityResolution",
    "IdentityResolutionOutcome",
    "IdentityResolutionPolicy",
    "DEFAULT_IDENTITY_RESOLUTION_POLICY",
    "build_identity_decision_record",
    "classify_identity_outcome",
    "compute_identity_decision_id",
    "merge_identity",
    "record_identity_decision",
    "remove_identity_alias",
    "resolve_identity",
    "split_identity",
    "unmerge_identity",
    # Contributions (PR005)
    "ContributionAssertionStatus",
    "ContributionIdentityMention",
    "ContributionIntegrityReport",
    "ContributionMergeResult",
    "ContributionSourceKind",
    "ContributionStatus",
    "DurableAssertionSupport",
    "GraphContribution",
    "GraphContributionAssertion",
    "GraphContributionAssertionCorrection",
    "build_assertion",
    "build_contribution_integrity_report",
    "compute_assertion_id",
    "compute_contribution_id",
    "compute_contribution_payload_sha256",
    "compute_contribution_source_payload_sha256",
    "compute_correction_digest",
    "correct_edge_assertion_support",
    "contradict_edge_assertion_support",
    "create_edge_assertion_correction_contribution",
    "create_edge_assertion_contradiction_contribution",
    "create_graph_contribution",
    "merge_contribution_to_revision",
    "rebuild_from_contributions",
    "retract_graph_contribution",
    "supersede_graph_contribution",
    # Temporal envelope (TL00)
    "TEMPORAL_ENVELOPE_SCHEMA",
    "TemporalCertainty",
    "TemporalEnvelopeV1",
    "TemporalExtentV1",
    "TemporalIntervalExtentV1",
    "TemporalIntervalV1",
    "TemporalPointExtentV1",
    "TemporalPointKind",
    "TemporalPointV1",
    "TemporalRelation",
    "TemporalScopeFormat",
    "TemporalScopeInterpretationV1",
    "TemporalScopeValidationError",
    "interpret_temporal_scope",
    "serialize_temporal_envelope",
    "temporal_core_semantic_payload",
    "temporal_source_payload",
    # Projection (PR007A) + resident read runtime (OPT01)
    "WorldGraphProjectionError",
    "ProjectionReadContext",
    "ProjectionRequestObservation",
    "ResidentRevision",
    "begin_request_io",
    "build_projection_payload",
    "clear_world_read_runtime",
    "get_last_projection_observation",
    "get_request_io",
    "get_world_read_runtime",
    "load_world_graph_revision_with_integrity",
    "project_world_graph",
    "project_world_graph_from_context",
    "RequestIoCounters",
    "reset_request_io",
    "resolve_projection_admissibility",
    "resolve_projection_read_context",
    "search_world_graph_projection",
    "set_last_projection_observation",
    "validate_projection_request_policy",
    # Retrieval + source-anchor admission (PR010A)
    "AdmittedSourceAnchorMatch",
    "WorldGraphRetrievalError",
    "get_campaign_object",
    "get_object_evidence",
    "get_object_neighborhood",
    "read_source_anchor",
    "resolve_admitted_anchor_match",
    "search_campaign_graph",
]
