import {makeBackup,reviewBackup,restoredState} from './backup-model.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function openBackup({board,play,show,onRestored}){const $=s=>document.querySelector(s),text=JSON.stringify(makeBackup(board,play),null,2);let review=null;show('Back up & restore',`<p>Writing, decisions, presentation drafts and style · ${esc(board.title??board.id)}. Browser storage is local; save a copy outside the browser.</p><div class="theme-actions"><button id="downloadBackup">Download JSON</button><button id="copyBackup">Copy JSON</button></div><details><summary>Backup text · manual recovery</summary><textarea id="backupText" readonly>${esc(text)}</textarea></details><hr><label>Restore a local backup<input id="backupFile" type="file" accept=".json,application/json"></label><label>Or paste backup JSON<textarea id="restoreText"></textarea></label><button id="reviewBackup">Review restore</button><button id="applyRestore" disabled>Restore reviewed backup</button><p id="backupStatus" role="status"></p>`);
 const invalidate=()=>{review=null;$('#applyRestore').disabled=true};$('#restoreText').oninput=invalidate;
 $('#backupFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5_000_000)throw Error('Backup exceeds 5 MB');$('#restoreText').value=await file.text();invalidate();$('#backupStatus').textContent='File loaded locally · review before restoring'}catch(e){$('#backupStatus').textContent=e.message}};
 $('#downloadBackup').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=board.id+'-play-backup.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#backupStatus').textContent='Download requested · verify the file in your downloads. Backup text is also available.'};$('#copyBackup').onclick=async()=>{try{await navigator.clipboard.writeText(text);$('#backupStatus').textContent='Backup JSON copied · save it to a private file'}catch{$('#backupStatus').textContent='Clipboard unavailable · use Backup text for manual copying'}};
 $('#reviewBackup').onclick=()=>{try{review=reviewBackup($('#restoreText').value,board);$('#applyRestore').disabled=false;$('#backupStatus').textContent=`Review: ${review.summary.notes} characters of shared writing; ${review.summary.sceneNotes} scene notes; ${review.summary.decisions} decisions; ${review.summary.compositions} compositions. ${review.previousRevision?'Restores under its previous source revision; current writing is unchanged.':'Current state will be archived before replacement.'} ${review.orphaned.length} unmatched scene references retained.`}catch(e){invalidate();$('#backupStatus').textContent=e.message}};
 $('#applyRestore').onclick=()=>{try{if(!review)throw Error('Review a backup first');const base='dmb-private-board-v1:'+board.id+':';const target=base+review.backup.sourcePin;const previous=localStorage.getItem(target);if(previous!==null)localStorage.setItem(target+':before-restore:'+new Date().toISOString(),previous);const next=review.previousRevision?review.backup.play:restoredState(review,board);localStorage.setItem(target,JSON.stringify(next));if(review.previousRevision){$('#backupStatus').textContent='Previous revision restored. Reload and use Recover previous writing to copy it explicitly.';invalidate()}else{$('#inspector').close();onRestored(next)}}catch(e){$('#backupStatus').textContent='Restore did not complete: '+e.message}};
}
