import {validateComposition,proposeComposition,applyComposition,renderComposition,compositionFromText} from './presentation-model.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kinds={paragraph:'Paragraph',heading:'Heading',read_aloud:'Read aloud',gm_note:'GM note',list:'List',media:'Source image / map'};
export function openComposer({board,card,lens,play,show,save,render}){
 const $=s=>document.querySelector(s),key=card.id+':'+lens;const basis={board,cardId:card.id,lens,currentComposition:play.compositions?.[key]};
 let blocks=structuredClone(play.compositionDrafts?.[key]??basis.currentComposition??compositionFromText(play.edits?.[key]??card.lenses[lens].map(i=>i.text).join('\n\n'))),proposal=null,undo=[];
 show('Compose '+lens,`<p class="composer-intro">Your preparation. Add blocks, write, then preview and Apply. Original evidence remains available.</p><div class="theme-actions"><select id="blockType" aria-label="Block type">${Object.entries(kinds).map(([id,name])=>'<option value="'+id+'">'+name+'</option>').join('')}</select><button id="addBlock">Add block</button><button id="undoBlock" disabled>Undo block change</button></div><div id="blockFields"></div><small id="draftStatus" role="status"></small><details><summary>Advanced · JSON / agent-authored block proposal</summary><textarea id="compositionJson" class="theme-editor"></textarea><button id="loadBlockJson">Load into draft</button><p>Typed local blocks only. Loading does not Apply; source/media restrictions still apply. This is not the native World Agent.</p></details><div class="theme-actions"><button id="previewComposition">Preview</button><button id="applyComposition" disabled>Apply composition</button><button id="resetComposition">Restore source projection</button></div><p id="compositionStatus" class="theme-status" role="status"></p><article id="compositionPreview" hidden></article>`);
 function invalidate(){proposal=null;$('#applyComposition').disabled=true;$('#compositionPreview').hidden=true;$('#compositionJson').value=JSON.stringify(blocks,null,2);play.compositionDrafts??={};play.compositionDrafts[key]=structuredClone(blocks);save($('#draftStatus'));$('#undoBlock').disabled=!undo.length}
 function remember(){undo.push(structuredClone(blocks));if(undo.length>50)undo.shift()}
 function fields(){
  $('#blockFields').innerHTML=blocks.map((b,i)=>`<section class="block-field"><div class="block-field__tools"><strong>${i+1}. ${esc(kinds[b.type])}</strong><button data-move="${i}:up" aria-label="Move block ${i+1} up" ${i===0?'disabled':''}>↑</button><button data-move="${i}:down" aria-label="Move block ${i+1} down" ${i===blocks.length-1?'disabled':''}>↓</button><button data-remove="${i}" aria-label="Remove block ${i+1}">Remove</button></div>${b.type==='media'?`<label>Selected source media<select data-asset="${i}">${board.assets.map(a=>'<option value="'+esc(a.id)+'" '+(a.id===b.assetId?'selected':'')+'>'+esc(a.title)+'</option>').join('')}</select></label><label>Caption<input data-caption="${i}" value="${esc(b.caption??'')}"></label><small>GM reference · player-safe review pending</small>`:b.type==='list'?`<label>List items · one per line<textarea data-items="${i}">${esc(b.items.join('\n'))}</textarea></label>`:`${b.type==='heading'?'<label>Heading level<select data-level="'+i+'">'+[2,3,4].map(l=>'<option '+(l===(b.level??3)?'selected':'')+'>'+l+'</option>').join('')+'</select></label>':''}<label>${b.type==='read_aloud'?'Your read-aloud text':b.type==='gm_note'?'GM information':'Text'}<textarea data-text="${i}">${esc(b.text)}</textarea></label>`}</section>`).join('');
  document.querySelectorAll('[data-text]').forEach(el=>el.oninput=()=>{blocks[Number(el.dataset.text)].text=el.value;invalidate()});document.querySelectorAll('[data-items]').forEach(el=>el.oninput=()=>{blocks[Number(el.dataset.items)].items=el.value.split('\n');invalidate()});document.querySelectorAll('[data-caption]').forEach(el=>el.oninput=()=>{blocks[Number(el.dataset.caption)].caption=el.value;invalidate()});document.querySelectorAll('[data-level]').forEach(el=>el.onchange=()=>{remember();blocks[Number(el.dataset.level)].level=Number(el.value);invalidate()});document.querySelectorAll('[data-asset]').forEach(el=>el.onchange=()=>{remember();blocks[Number(el.dataset.asset)].assetId=el.value;invalidate()});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{remember();blocks.splice(Number(el.dataset.remove),1);fields();invalidate()});document.querySelectorAll('[data-move]').forEach(el=>el.onclick=()=>{remember();const [index,direction]=el.dataset.move.split(':');const i=Number(index),j=i+(direction==='up'?-1:1);[blocks[i],blocks[j]]=[blocks[j],blocks[i]];fields();invalidate()});
 }
 $('#addBlock').onclick=()=>{const type=$('#blockType').value;if(type==='media'&&!board.assets.length){$('#compositionStatus').textContent='No selected media exists in this dataset.';return}remember();blocks.push(type==='media'?{type,assetId:board.assets[0].id,caption:''}:type==='list'?{type,items:['']}:{type,text:'',...(type==='heading'?{level:3}:{})});fields();invalidate();$('#blockFields').lastElementChild?.scrollIntoView({block:'nearest'})};
 $('#undoBlock').onclick=()=>{if(undo.length){blocks=undo.pop();fields();invalidate()}};
 $('#loadBlockJson').onclick=()=>{try{const next=validateComposition(JSON.parse($('#compositionJson').value),board);remember();blocks=next;fields();invalidate();$('#compositionStatus').textContent='Loaded into your draft · not applied'}catch(e){$('#compositionStatus').textContent=e.message}};
 $('#previewComposition').onclick=()=>{try{proposal=proposeComposition({...basis,blocks});$('#compositionPreview').innerHTML=renderComposition(proposal.blocks,board);$('#compositionPreview').hidden=false;$('#applyComposition').disabled=false;$('#compositionStatus').textContent='Preview · authored adaptation, not a source claim or played event';$('#compositionPreview').scrollIntoView({block:'nearest'})}catch(e){$('#compositionStatus').textContent=e.message}};
 function archive(){play.presentationHistory??=[];play.presentationHistory.push({key,at:new Date().toISOString(),composition:structuredClone(play.compositions?.[key]??null),text:play.edits?.[key]??null});}
 $('#applyComposition').onclick=()=>{try{const result=applyComposition(proposal,{...basis,currentComposition:play.compositions?.[key]});archive();play.compositions??={};play.compositions[key]=result;delete play.compositionDrafts?.[key];save();$('#inspector').close();render()}catch(e){$('#compositionStatus').textContent=e.message}};
 $('#resetComposition').onclick=()=>{archive();if(play.compositions)delete play.compositions[key];if(play.edits)delete play.edits[key];if(play.compositionDrafts)delete play.compositionDrafts[key];save();$('#inspector').close();render()};fields();$('#compositionJson').value=JSON.stringify(blocks,null,2);$('#draftStatus').textContent=play.compositionDrafts?.[key]?'Recovered unapplied draft · this browser':'Draft stays separate from the displayed card';
}
