import {webcrypto} from 'node:crypto';
globalThis.crypto=webcrypto;
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parse,validate,editCard,recordOutcome,rooms,markerSignature} from './model.js';
const docs=JSON.parse(fs.readFileSync(new URL('./content.json',import.meta.url)));
const session=docs[0].markdown,house=docs[1].markdown;
const p=parse(session);assert.equal(p.elements.length,90);assert.equal(p.scenes.length,19);assert.equal(p.elements.filter(x=>x.kind==='beat').length,10);assert.equal(p.elements.filter(x=>x.kind==='choice').length,9);assert.equal(p.elements.filter(x=>x.kind==='option').length,52);
assert.equal(parse(house).scenes.length,7);assert.equal(rooms(house).length,9);assert.ok(rooms(house).find(x=>x.title==="Lysandra's Old Room").text.includes('wooden soldier'));
const scene=p.scenes[0],originalBody=session.slice(scene.bodyStart,scene.end),edited=editCard(session,scene.id,originalBody+'\n\nPrototype prep: a runner holds a spare blanket.');assert.deepEqual(validate(edited,session),[]);assert.deepEqual(markerSignature(edited),markerSignature(session));assert.ok(edited.startsWith(session.slice(0,scene.bodyStart)));assert.ok(edited.endsWith(session.slice(scene.end)));
assert.ok(validate(edited.replace('option:tail-rescue','option:gone'),session).length||validate(edited.replace('kind=scene','kind=beat'),session).length);
const choices=p.elements.filter(e=>e.kind==='option').slice(0,2).map(e=>e.id);const state=recordOutcome({drafts:[edited],outcomes:[]},0,scene.id,choices,'The townsfolk rescued sleepers while the party blocked the route.');assert.equal(state.drafts[0],edited);assert.equal(state.outcomes.length,1);assert.deepEqual(state.outcomes[0].choices,choices);assert.throws(()=>recordOutcome(state,0,scene.id,[],''));
assert.equal(JSON.parse(JSON.stringify(state)).drafts[0],edited);assert.deepEqual(parse(state.drafts[0]).scenes.map(x=>x.id),p.scenes.map(x=>x.id));
console.log('PASS: exact fixture structure; 9 rooms; edit boundary; stable marker guards; simultaneous actions; separate outcome; serialization continuity');
const {createScene,roomBlocks}=await import('./model.js');
assert.throws(()=>createScene(['','','','','',''],'scene:local-test'));
assert.throws(()=>createScene(['Blanket line','People wait','A runner approaches','What do you do?','Unstructured choice',''],'scene:local-test'));
const created=createScene(['Blanket line','People wait','A runner approaches','What do you do?','Help | people settle\nRest | someone else takes over','Existing place reference: Ironveil Warehouse'],'scene:local-test');
assert.equal(parse(created).scenes.length,1);assert.equal(parse(created).elements.filter(x=>x.kind==='option').length,3);assert.ok(created.includes('Something unexpected'));assert.deepEqual(validate(session+created,session),[]);assert.equal(roomBlocks(rooms(house)[8].text).length,6);
console.log('PASS: guided creation required blocks, structured consequences, unexpected path and room focus');
assert.ok(validate(session+'\n[Invented](dmb-node:node:made-up)',session).some(x=>x.includes('Unverified node')));
assert.deepEqual(validate(house+'\n[Lysandra](dmb-node:node:captain-lysandra-ironveil)',house,['node:captain-lysandra-ironveil']),[]);
console.log('PASS: unknown node link rejected; explicit verified identity accepted across documents');
const last=p.scenes.at(-1),lastBody=session.slice(last.bodyStart,last.end);assert.ok(!lastBody.includes('# GM Running Notes'));const lastEdited=editCard(session,last.id,lastBody+'\nLocal test.');assert.ok(lastEdited.includes('# GM Running Notes'));assert.deepEqual(markerSignature(lastEdited),markerSignature(session));const houseLast=parse(house).scenes.at(-1);assert.ok(!house.slice(houseLast.bodyStart,houseLast.end).includes('## House Tone'));assert.ok(editCard(house,houseLast.id,house.slice(houseLast.bodyStart,houseLast.end)+'\nLocal test.').includes('## House Tone'));
console.log('PASS: global running notes/tone remain outside scene-edit boundaries');
const {directionEffects}=await import('./model.js');
const directions='<!-- dmb-playable-element:v2 kind=beat id=beat:b -->\n## B\n<!-- dmb-playable-element:v2 kind=scene id=scene:a -->\n### A\n<!-- dmb-playable-element:v2 kind=option id=option:a suppresses=beat:b -->\n- **Go elsewhere**\n<!-- dmb-playable-element:v2 kind=option id=option:b activates=beat:b -->\n- **Return**';
assert.equal(directionEffects(directions,[{document:0,scene:'scene:a',id:'1',choices:['option:a']}],0)[0].effect.status,'not-planned');
assert.equal(directionEffects(directions,[{document:0,id:'1',choices:['option:a']},{document:0,id:'2',choices:['option:b']}],0)[0].effect.status,'available');
assert.equal(directionEffects(directions,[{document:1,id:'1',choices:['option:a']}],0).length,0);
console.log('PASS: recorded directions flag Beat scenes, later activation restores relevance, documents stay isolated');
