export function parse(markdown){const matches=[...markdown.matchAll(/<!-- dmb-playable-element:v2 (.*?) -->/g)];const elements=matches.map((m,i)=>({...Object.fromEntries([...m[1].matchAll(/(\w+)=(\S+)/g)].map(x=>[x[1],x[2]])),start:m.index,bodyStart:m.index+m[0].length,end:matches[i+1]?.index??markdown.length}));let beat=null;const scenes=[];for(const e of elements){if(e.kind==='beat')beat=e;if(e.kind==='scene'){const following=elements.find(x=>x.start>e.start&&['scene','beat'].includes(x.kind));const markedEnd=following?.start??markdown.length;const globalHeading=markdown.slice(e.bodyStart,markedEnd).match(/^#{1,2} /m);const sceneEnd=globalHeading?e.bodyStart+globalHeading.index:markedEnd;scenes.push({...e,end:sceneEnd,beat:beat?.id,title:markdown.slice(e.bodyStart,e.end).match(/^### (.+)/m)?.[1]??e.id})}}return {elements,scenes};}
export function validate(markdown,original,knownNodes=[]){const now=parse(markdown).elements,old=parse(original).elements;const problems=[];const permitted=new Set([...knownNodes,...[...original.matchAll(/\]\(dmb-node:([^)]+)\)/g)].map(x=>x[1])]);for(const match of markdown.matchAll(/\]\(dmb-node:([^)]+)\)/g))if(!permitted.has(match[1]))problems.push('Unverified node reference '+match[1]);const ids=now.map(x=>x.id);for(const e of now){if(!e.id||!['beat','scene','choice','option'].includes(e.kind))problems.push('Invalid marker identity or kind.');if(e.kind==='choice'&&e.scene&&!now.some(x=>x.id===e.scene&&x.kind==='scene'))problems.push('Missing choice scene '+e.scene);}if(new Set(ids).size!==ids.length)problems.push('Every stable ID must be unique.');for(const marker of markerSignature(original))if(!markerSignature(markdown).includes(marker))problems.push('Preserve existing marker '+marker);for(const m of markdown.matchAll(/(?:activates|suppresses)=([^\s>]+)/g))for(const id of m[1].split(','))if(!ids.includes(id))problems.push('Missing target '+id);return problems;}
export function editCard(markdown,sceneId,body){const {scenes}=parse(markdown),s=scenes.find(x=>x.id===sceneId);if(!s)throw Error('Scene not found');return markdown.slice(0,s.bodyStart)+'\n'+body.trim()+'\n\n'+markdown.slice(s.end);}
export function recordOutcome(state,doc,scene,choices,note){if(!note.trim()&&!choices.length)throw Error('Choose actions or write an outcome.');return {...state,outcomes:[...(state.outcomes??[]),{id:crypto.randomUUID(),document:doc,scene,choices:[...choices],note,at:new Date().toISOString(),status:'LOCAL PROTOTYPE OUTCOME'}]};}
export function sceneBlocks(body){const parts=body.split(/(?=^\*\*(?:Situation|Read aloud|Do now|GM only|Relevant|Missing reference|PREP LOCK[^*]*|Ground floor|Upper floor)\*\*\s*$)/m);return parts.filter(x=>x.trim()&&!/^### [^\n]+\s*$/.test(x.trim())).map((text,i)=>({id:'block:'+i,title:text.match(/^\*\*([^*]+)\*\*/)?.[1]??'Overview',text}));}
export function rooms(markdown){const s=parse(markdown).scenes.find(x=>x.id==='scene:ironveil-house-map');if(!s)return [];const body=markdown.slice(s.bodyStart,s.end);const names=['Front Mudroom','Family Kitchen','Sitting Room',"Lysandro's Workshop",'Back Yard',"Parents' Room","Calyx's Room","Torr's Room / Study","Lysandra's Old Room"];const matches=[...body.matchAll(/^\*\*([^*]+)\*\*\s*$/gm)].filter(m=>names.includes(m[1]));return matches.map((m,i)=>({id:'space:'+i,title:m[1],text:body.slice(m.index,matches[i+1]?.index??(body.indexOf('<!-- dmb-playable-element:v2 kind=choice')>=0?body.indexOf('<!-- dmb-playable-element:v2 kind=choice'):body.length))}));}
export function markerSignature(markdown){return [...markdown.matchAll(/<!-- dmb-playable-element:v2 .*? -->/g)].map(x=>x[0]);}
export function roomBlocks(text){const sections=[...text.matchAll(/^(Current contents:|Still hers:|Inside the desk[^\n]*|Possible finds:|The key tone:)\s*$/gm)];if(!sections.length)return [{title:'Room detail',text}];const result=[{title:'Character / context',text:text.slice(0,sections[0].index)}];for(let i=0;i<sections.length;i++)result.push({title:sections[i][1].replace(':','').replace(/^Inside the desk.*/,'Papers / investigation'),text:text.slice(sections[i].index,sections[i+1]?.index??text.length)});return result;}
export function createScene(values,id){
 const [name,situation,readAloud,prompt,choiceText,references]=values;
 if([name,situation,readAloud,prompt].some(x=>!x.trim()))throw Error('Name, situation, read aloud and immediate prompt are required.');
 if(/<!--|dmb-node:/.test(values.join(' ')))throw Error('Raw markers and unverified node links are not allowed in guided creation.');
 if(!/^scene:local-[a-z0-9-]+$/.test(id))throw Error('Invalid local scene identity.');
 const options=choiceText.split('\n').filter(x=>x.trim()).map(line=>{const pair=line.split('|').map(x=>x.trim());if(pair.length!==2||pair.some(x=>!x))throw Error('Use Action | consequence for each choice.');return pair});
 let source=`\n\n<!-- dmb-playable-element:v2 kind=scene id=${id} -->\n### ${name}\n\n**PREP / PROPOSED — local prototype**\n\n**Situation**\n\n${situation}\n\n**Read aloud**\n\n> ${readAloud.replaceAll('\n','\n> ')}\n\n**Do now**\n\n${prompt}\n\n**Relevant**\n\n${references||'No new graph identities admitted.'}\n`;
 if(options.length){const suffix=id.slice(6);source+=`\n<!-- dmb-playable-element:v2 kind=choice id=choice:${suffix} scene=${id} -->\n### What do they do?\n\nMultiple activities may happen simultaneously.\n`;options.forEach(([action,consequence],i)=>source+=`\n<!-- dmb-playable-element:v2 kind=option id=option:${suffix}-${i} -->\n- **${action}**\n\n  Consequence: ${consequence}\n`);source+=`\n<!-- dmb-playable-element:v2 kind=option id=option:${suffix}-unexpected -->\n- **Something unexpected.**\n\n  Follow player intent and record the actual outcome.\n`}
 return source;
}
export function directionEffects(markdown,outcomes,doc){
 const parsed=parse(markdown),effects=new Map();
 for(const outcome of outcomes.filter(o=>o.document===doc))for(const id of outcome.choices){
  const option=parsed.elements.find(e=>e.kind==='option'&&e.id===id);
  for(const [attribute,status] of [['activates','available'],['suppresses','not-planned']])for(const target of (option?.[attribute]??'').split(',').filter(Boolean))effects.set(target,{status,scene:outcome.scene,outcome:outcome.id});
 }
 return parsed.scenes.map(scene=>({scene:scene.id,effect:effects.get(scene.id)??effects.get(scene.beat)})).filter(x=>x.effect);
}
