import {themePresets,validateTheme,proposeTheme,applyThemeProposal} from './theme-model.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colorFields={paper:'Paper',ink:'Text',accent:'Accent',muted:'Secondary text',workspace:'Workspace',chrome:'Navigation'};
const numberFields={fontSize:['Text size',12,24,1,'px'],lineHeight:['Line spacing',1.2,2,.02,''],cardPadding:['Card padding',12,48,1,'px'],cardRadius:['Corner radius',0,24,1,'px'],readingWidth:['Reading width',600,1600,20,'px']};
const fonts=['Georgia','system-ui','serif','sans-serif','monospace'];
export function openThemeEditor({board,play,show,paint,save,render}){
 const $=s=>document.querySelector(s);let draft=validateTheme(play.theme??themePresets.baseline),proposal=null;
 show('Style this adventure',`<p>Adjust the canvas live, then Apply to save. Your source and play writing stay separate.</p><label>Starting style<select id="themePreset">${Object.entries(themePresets).map(([id,t])=>`<option value="${id}">${esc(t.name)}</option>`).join('')}</select></label><label>Style name<input id="themeName" maxlength="100"></label><div class="theme-color-grid">${Object.entries(colorFields).map(([key,label])=>`<label>${label}<input type="color" data-theme-field="${key}" aria-label="${label} color"></label>`).join('')}</div><div class="theme-font-grid">${[['headingFont','Headings'],['bodyFont','Body text']].map(([key,label])=>`<label>${label}<select data-theme-field="${key}" aria-label="${label}">${fonts.map(f=>`<option>${f}</option>`).join('')}</select></label>`).join('')}</div>${Object.entries(numberFields).map(([key,[label,min,max,step]])=>`<label class="theme-range">${label}<output data-theme-value="${key}"></output><input type="range" data-theme-field="${key}" aria-label="${label}" min="${min}" max="${max}" step="${step}"></label>`).join('')}<details><summary>Advanced · JSON configuration</summary><textarea id="themeJson" class="theme-editor" aria-label="Theme JSON"></textarea><p>Typed local presentation only. No native World Agent is called.</p></details><div class="theme-actions"><button id="previewTheme">Preview proposal</button><button id="applyTheme" disabled>Apply style</button><button id="cancelTheme">Cancel preview</button><button id="resetTheme">Restore design v1</button></div><p id="themeStatus" class="theme-status" role="status"></p>`,'pane');
 const sync=()=>{$('#themeName').value=draft.name;for(const input of document.querySelectorAll('[data-theme-field]'))input.value=draft[input.dataset.themeField];for(const output of document.querySelectorAll('[data-theme-value]')){const key=output.dataset.themeValue;output.value=draft[key]+numberFields[key][4]}$('#themeJson').value=JSON.stringify(draft,null,2)};
 const preview=()=>{proposal=null;$('#applyTheme').disabled=true;try{proposal=proposeTheme({boardId:board.id,sourcePin:board.pin,currentTheme:play.theme,nextTheme:draft});paint(proposal.theme);$('#applyTheme').disabled=false;$('#themeStatus').textContent='Live preview · not saved. Apply when ready.'}catch(e){$('#themeStatus').textContent=e.message}};
 sync();$('#themePreset').onchange=e=>{draft=structuredClone(themePresets[e.target.value]);sync();preview()};$('#themeName').oninput=e=>{draft.name=e.target.value;$('#themeJson').value=JSON.stringify(draft,null,2);preview()};
 for(const input of document.querySelectorAll('[data-theme-field]'))input.oninput=()=>{const key=input.dataset.themeField;draft[key]=Object.hasOwn(numberFields,key)?Number(input.value):input.value;sync();preview()};
 $('#themeJson').oninput=()=>{proposal=null;$('#applyTheme').disabled=true;try{draft=validateTheme(JSON.parse($('#themeJson').value));sync();preview()}catch(e){$('#themeStatus').textContent=e.message}};$('#previewTheme').onclick=preview;
 $('#applyTheme').onclick=()=>{try{play.theme=applyThemeProposal(proposal,{boardId:board.id,sourcePin:board.pin,currentTheme:play.theme});save();$('#inspector').close();render()}catch(e){$('#themeStatus').textContent=e.message}};
 $('#cancelTheme').onclick=()=>{paint(play.theme);$('#inspector').close()};$('#resetTheme').onclick=()=>{delete play.theme;save();$('#inspector').close();render()};
}
