"""Surface-neutral Markdown mention linker (PR #413).

Owns the byte-identity invariant for the hoist: the characterization fixture in
``tests/fixtures/markdown_mention_characterization_v1.json`` was generated by the
UNMODIFIED recap entry point at base ``4b40e68a`` and is replayed here against
both the neutral linker and the recap adapter.
"""

from __future__ import annotations

import ast
import inspect
import json
from pathlib import Path
from typing import Any

import pytest

from graph_memory.projection import markdown_mentions
from graph_memory.projection.markdown_mentions import (
    AMBIGUOUS_MENTION_DIAGNOSTIC,
    LocatedMentionBinding,
    MarkdownMention,
    MarkdownMentionDiagnostic,
    MentionBinding,
    project_markdown_mentions,
    splice_node_link_spans,
)
from graph_memory.projection.world_projection import WorldGraphProjectionNodeView
from graph_memory.projection.world_recap_projection import (
    project_world_markdown_mentions,
)

FIXTURE_PATH = (
    Path(__file__).parent / "fixtures" / "markdown_mention_characterization_v1.json"
)
CHARACTERIZATION_BASE_SHA = "4b40e68aad166b9dc59e797df851e2549bd6e354"

# Modules whose vocabulary must never reach the neutral linker.
FORBIDDEN_IMPORT_MODULES = {
    "graph_memory.projection.world_projection",
    "graph_memory.projection.world_recap_projection",
    "graph_memory.projection.recap_projection",
    "graph_memory.projection.node_view",
    "graph_memory.projection.focus_overlay",
}


def _load_fixture() -> dict[str, Any]:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


FIXTURE = _load_fixture()
CASES: list[dict[str, Any]] = FIXTURE["cases"]
CASE_IDS = [case["case_id"] for case in CASES]


def _node_views(specs: list[dict[str, Any]]) -> list[WorldGraphProjectionNodeView]:
    return [
        WorldGraphProjectionNodeView(
            node_id=spec["node_id"],
            label=spec["label"],
            kind="npc",
            role="character",
            aliases=list(spec["aliases"]),
        )
        for spec in specs
    ]


def _bindings(specs: list[dict[str, Any]]) -> list[MentionBinding]:
    """The documented adapter rule: node order, label first, duplicates kept."""
    return [
        MentionBinding(surface=raw, node_id=spec["node_id"])
        for spec in specs
        for raw in (spec["label"], *spec["aliases"])
    ]


def test_characterization_fixture_provenance() -> None:
    assert FIXTURE["schema"] == "dmb_markdown_mention_characterization_v1"
    assert FIXTURE["base_sha"] == CHARACTERIZATION_BASE_SHA
    # The fixture is only proof if it actually exercises linking and ambiguity.
    assert len(CASES) >= 60
    assert sum(1 for case in CASES if case["mentions"]) >= 15
    assert sum(1 for case in CASES if case["diagnostics"]) >= 4
    assert len(set(CASE_IDS)) == len(CASE_IDS)


@pytest.mark.parametrize("case", CASES, ids=CASE_IDS)
def test_neutral_linker_replays_base_characterization(case: dict[str, Any]) -> None:
    projected, mentions, diagnostics = project_markdown_mentions(
        case["markdown"],
        _bindings(case["nodes"]),
    )
    assert projected == case["projected_markdown"]
    assert [
        [m.mention_id, m.node_id, m.label, m.start_offset, m.end_offset]
        for m in mentions
    ] == case["mentions"]
    assert [
        [d.code, d.message, d.severity] for d in diagnostics
    ] == case["diagnostics"]


@pytest.mark.parametrize("case", CASES, ids=CASE_IDS)
def test_recap_adapter_replays_base_characterization(case: dict[str, Any]) -> None:
    projected, mentions, diagnostics = project_world_markdown_mentions(
        case["markdown"],
        _node_views(case["nodes"]),
    )
    assert projected == case["projected_markdown"]
    assert [
        [m.mention_id, m.node_id, m.label, m.start_offset, m.end_offset]
        for m in mentions
    ] == case["mentions"]
    assert [
        [d.code, d.message, d.severity] for d in diagnostics
    ] == case["diagnostics"]
    # Recap wire shape is unchanged: mentions stay navigation-only.
    assert all(m.evidence_ref_ids == [] for m in mentions)


def test_no_surface_imports() -> None:
    """The neutral module must not import graph/recap/surface vocabulary."""
    source = Path(inspect.getfile(markdown_mentions)).read_text(encoding="utf-8")
    imported: set[str] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)
            imported.update(f"{node.module}.{alias.name}" for alias in node.names)

    assert not (imported & FORBIDDEN_IMPORT_MODULES), imported & FORBIDDEN_IMPORT_MODULES
    assert not any(name.startswith("apps.") for name in imported), imported
    assert not any(
        name.startswith("graph_memory.") for name in imported
    ), imported


def test_no_surface_imports_in_public_signature() -> None:
    """No graph, recap, or surface type may appear in the public signature."""
    signature = inspect.signature(project_markdown_mentions)
    rendered = str(signature)
    for token in ("World", "Recap", "Graph", "Node View", "focus", "surface_owner"):
        assert token not in rendered, rendered

    binding_param = signature.parameters["bindings"]
    assert binding_param.annotation is not inspect.Parameter.empty
    assert MentionBinding.model_fields.keys() == {"surface", "node_id"}
    assert set(MarkdownMention.model_fields) == {
        "mention_id",
        "node_id",
        "label",
        "start_offset",
        "end_offset",
    }
    assert set(MarkdownMentionDiagnostic.model_fields) == {
        "code",
        "message",
        "severity",
    }
    assert MarkdownMentionDiagnostic.model_fields["severity"].is_required()
    assert MarkdownMentionDiagnostic.model_fields["code"].is_required()
    assert MarkdownMentionDiagnostic.model_fields["message"].is_required()


def test_binding_order_preserves_ambiguity_sample_casing() -> None:
    """The diagnostic quotes the FIRST bound surface, with its original casing."""
    first = [
        MentionBinding(surface="Caelynn", node_id="pc:caelynn"),
        MentionBinding(surface="caelynn", node_id="npc:caelynn-double"),
    ]
    _projected, _mentions, diagnostics = project_markdown_mentions(
        "CAELYNN arrived.", first
    )
    assert len(diagnostics) == 1
    assert diagnostics[0].code == AMBIGUOUS_MENTION_DIAGNOSTIC
    assert diagnostics[0].severity == "warning"
    assert "'Caelynn'" in diagnostics[0].message

    _projected, _mentions, reversed_diagnostics = project_markdown_mentions(
        "CAELYNN arrived.", list(reversed(first))
    )
    assert len(reversed_diagnostics) == 1
    assert "'caelynn'" in reversed_diagnostics[0].message
    # Only the sample casing moves; the owner list stays sorted and stable.
    assert "(npc:caelynn-double, pc:caelynn)" in reversed_diagnostics[0].message


def test_binding_order_survives_the_recap_adapter() -> None:
    """The adapter must emit label-before-aliases, node order, duplicates kept."""
    nodes = [
        WorldGraphProjectionNodeView(
            node_id="npc:first",
            label="cAeLyNn",
            kind="npc",
            role="character",
            aliases=["CaElYnN"],
        ),
        WorldGraphProjectionNodeView(
            node_id="npc:second",
            label="CAELYNN",
            kind="npc",
            role="character",
            aliases=["caelynn"],
        ),
    ]
    _projected, _mentions, diagnostics = project_world_markdown_mentions(
        "Then CAELYNN spoke.", nodes
    )
    assert len(diagnostics) == 1
    assert "'cAeLyNn'" in diagnostics[0].message

    _projected, _mentions, reversed_diagnostics = project_world_markdown_mentions(
        "Then CAELYNN spoke.", list(reversed(nodes))
    )
    assert "'CAELYNN'" in reversed_diagnostics[0].message


def test_duplicate_bindings_are_not_deduplicated_before_ambiguity_check() -> None:
    """A surface repeated for the SAME node stays unique, not ambiguous."""
    bindings = [
        MentionBinding(surface="Caelynn", node_id="pc:caelynn"),
        MentionBinding(surface="Caelynn", node_id="pc:caelynn"),
        MentionBinding(surface="caelynn", node_id="pc:caelynn"),
    ]
    projected, mentions, diagnostics = project_markdown_mentions(
        "Caelynn stood watch.", bindings
    )
    assert projected == "[Caelynn](dmb-node:pc:caelynn) stood watch."
    assert len(mentions) == 1
    assert diagnostics == []


def test_ambiguity_is_reported_once_per_casefolded_key() -> None:
    bindings = [
        MentionBinding(surface="River", node_id="npc:river-guide"),
        MentionBinding(surface="river", node_id="location:river"),
        MentionBinding(surface="RIVER", node_id="npc:river-guide"),
    ]
    projected, mentions, diagnostics = project_markdown_mentions(
        "River flooded. The river rose. RIVER again.", bindings
    )
    assert projected == "River flooded. The river rose. RIVER again."
    assert mentions == []
    assert len(diagnostics) == 1


def test_ambiguity_not_reported_when_only_match_is_protected() -> None:
    bindings = [
        MentionBinding(surface="Caelynn", node_id="npc:first"),
        MentionBinding(surface="Caelynn", node_id="npc:second"),
    ]
    projected, mentions, diagnostics = project_markdown_mentions(
        "Inline `Caelynn` only.", bindings
    )
    assert projected == "Inline `Caelynn` only."
    assert mentions == []
    assert diagnostics == []


def test_unique_surface_uses_durable_node_ids() -> None:
    bindings = [
        MentionBinding(surface="Caelynn", node_id="pc:caelynn"),
        MentionBinding(surface="Caelynn Leafwhisper", node_id="pc:caelynn"),
        MentionBinding(surface="Mireward Reach", node_id="location:mireward"),
        MentionBinding(surface="Mireward", node_id="location:mireward"),
    ]
    projected, mentions, diagnostics = project_markdown_mentions(
        "Caelynn reached Mireward before nightfall.", bindings
    )
    assert "[Caelynn](dmb-node:pc:caelynn)" in projected
    assert "[Mireward](dmb-node:location:mireward)" in projected
    assert {m.node_id for m in mentions} == {"pc:caelynn", "location:mireward"}
    assert diagnostics == []


def test_ambiguous_alias_does_not_first_win() -> None:
    bindings = [
        MentionBinding(surface="River", node_id="npc:river-guide"),
        MentionBinding(surface="River", node_id="npc:river-guide"),
        MentionBinding(surface="River", node_id="location:river"),
        MentionBinding(surface="River", node_id="location:river"),
    ]
    projected, mentions, diagnostics = project_markdown_mentions(
        "River flooded overnight.", bindings
    )
    assert projected == "River flooded overnight."
    assert mentions == []
    assert any(d.code == AMBIGUOUS_MENTION_DIAGNOSTIC for d in diagnostics)


def test_longest_unique_surface_wins() -> None:
    bindings = [
        MentionBinding(surface="Mireward Reach", node_id="location:mireward-reach"),
        MentionBinding(surface="Mireward", node_id="location:mireward-reach"),
    ]
    projected, mentions, _diagnostics = project_markdown_mentions(
        "They entered Mireward Reach at dusk.", bindings
    )
    assert "[Mireward Reach](dmb-node:location:mireward-reach)" in projected
    assert "[Mireward](dmb-node:" not in projected
    assert len(mentions) == 1


def test_longest_surface_wins_across_different_nodes() -> None:
    bindings = [
        MentionBinding(surface="Mireward", node_id="location:mireward"),
        MentionBinding(surface="Mireward Reach", node_id="location:mireward-reach"),
    ]
    projected, mentions, _diagnostics = project_markdown_mentions(
        "They entered Mireward Reach at dusk.", bindings
    )
    assert projected == (
        "They entered [Mireward Reach](dmb-node:location:mireward-reach) at dusk."
    )
    assert len(mentions) == 1
    assert mentions[0].node_id == "location:mireward-reach"


_PROTECTED_CASES = [
    case
    for case in CASES
    if case["origin"].endswith("test_protected_markdown_and_code_ranges_untouched")
]


def test_protected_case_corpus_is_present() -> None:
    """Guards the moved coverage: the base adversarial corpus must not shrink."""
    assert len(_PROTECTED_CASES) >= 20


@pytest.mark.parametrize(
    "case", _PROTECTED_CASES, ids=[case["case_id"] for case in _PROTECTED_CASES]
)
def test_protected_markdown_and_code_ranges_untouched(case: dict[str, Any]) -> None:
    markdown = case["markdown"]
    projected, mentions, _diagnostics = project_markdown_mentions(
        markdown, _bindings(case["nodes"])
    )
    assert projected == markdown, markdown
    assert mentions == []


def test_mention_id_uses_pre_splice_offset_while_offsets_are_post_splice() -> None:
    bindings = [MentionBinding(surface="Caelynn", node_id="pc:caelynn")]
    _projected, mentions, _diagnostics = project_markdown_mentions(
        "Caelynn spoke. Then Caelynn left.", bindings
    )
    assert len(mentions) == 2
    assert mentions[0].mention_id == "mention:pc:caelynn:0"
    assert (mentions[0].start_offset, mentions[0].end_offset) == (0, 30)
    # Second mention: id keeps the ORIGINAL start, offsets are post-splice.
    assert mentions[1].mention_id == "mention:pc:caelynn:20"
    assert mentions[1].start_offset == 43
    assert mentions[1].end_offset == 73


def test_blank_surface_is_skipped_without_diagnostic() -> None:
    bindings = [
        MentionBinding(surface="", node_id="pc:caelynn"),
        MentionBinding(surface="   ", node_id="pc:caelynn"),
        MentionBinding(surface="Caelynn", node_id="pc:caelynn"),
    ]
    projected, mentions, diagnostics = project_markdown_mentions(
        "Caelynn stood watch.", bindings
    )
    assert projected == "[Caelynn](dmb-node:pc:caelynn) stood watch."
    assert len(mentions) == 1
    assert diagnostics == []


def test_empty_inputs_return_unchanged() -> None:
    assert project_markdown_mentions("", []) == ("", [], [])
    assert project_markdown_mentions("", [MentionBinding(surface="x", node_id="n")]) == (
        "",
        [],
        [],
    )
    assert project_markdown_mentions("No matches here.", []) == (
        "No matches here.",
        [],
        [],
    )


def test_projection_is_deterministic_across_repeated_calls() -> None:
    bindings = [
        MentionBinding(surface="Caelynn", node_id="pc:caelynn"),
        MentionBinding(surface="River", node_id="npc:river-guide"),
        MentionBinding(surface="River", node_id="location:river"),
    ]
    markdown = "Caelynn crossed the River at dawn."
    first = project_markdown_mentions(markdown, bindings)
    for _ in range(5):
        assert project_markdown_mentions(markdown, bindings) == first


def test_splice_node_link_spans_is_importable_from_both_modules() -> None:
    """The recap re-export shim keeps existing service importers unchanged."""
    from graph_memory.projection.recap_projection import (
        splice_node_link_spans as reexported,
    )

    assert reexported is splice_node_link_spans


def test_located_binding_links_plain_prose_with_exact_offsets() -> None:
    projected, mentions, diagnostics = project_markdown_mentions(
        "Caelynn opened the door.",
        [],
        located_bindings=[
            LocatedMentionBinding(
                surface="Caelynn",
                node_id="pc:caelynn",
                start_offset=0,
                end_offset=7,
            )
        ],
    )
    assert projected == "[Caelynn](dmb-node:pc:caelynn) opened the door."
    assert len(mentions) == 1
    assert (mentions[0].start_offset, mentions[0].end_offset) == (0, 30)
    assert diagnostics == []


def test_located_binding_skips_protected_inline_code() -> None:
    markdown = "`Caelynn` waited."
    projected, mentions, diagnostics = project_markdown_mentions(
        markdown,
        [MentionBinding(surface="Caelynn", node_id="pc:caelynn")],
        located_bindings=[
            LocatedMentionBinding(
                surface="Caelynn",
                node_id="pc:caelynn",
                start_offset=1,
                end_offset=8,
            )
        ],
    )
    assert projected == markdown
    assert mentions == []
    assert diagnostics == []


def test_located_binding_occupies_range_before_free_text_match() -> None:
    """Free-text regex must not duplicate a span already claimed by a located binding."""
    projected, mentions, _diagnostics = project_markdown_mentions(
        "Caelynn and Caelynn again.",
        [MentionBinding(surface="Caelynn", node_id="pc:caelynn")],
        located_bindings=[
            LocatedMentionBinding(
                surface="Caelynn",
                node_id="pc:caelynn",
                start_offset=12,
                end_offset=19,
            )
        ],
    )
    assert projected == (
        "[Caelynn](dmb-node:pc:caelynn) and [Caelynn](dmb-node:pc:caelynn) again."
    )
    assert len(mentions) == 2
    assert [m.mention_id for m in mentions] == [
        "mention:pc:caelynn:0",
        "mention:pc:caelynn:12",
    ]


def test_invalid_located_binding_fails_closed_without_diagnostic() -> None:
    projected, mentions, diagnostics = project_markdown_mentions(
        "Caelynn stood watch.",
        [MentionBinding(surface="Caelynn", node_id="pc:caelynn")],
        located_bindings=[
            LocatedMentionBinding(
                surface="Wrong",
                node_id="pc:caelynn",
                start_offset=0,
                end_offset=7,
            )
        ],
    )
    assert projected == "[Caelynn](dmb-node:pc:caelynn) stood watch."
    assert len(mentions) == 1
    assert diagnostics == []


def test_located_binding_public_shape_is_surface_neutral() -> None:
    assert set(LocatedMentionBinding.model_fields) == {
        "surface",
        "node_id",
        "start_offset",
        "end_offset",
    }
