import type { PlayRunRecord, PlayRunReferenceManifestV2 } from "../../api/types";

export const BREACH_DOGFOOD_RUNBOOK_MARKDOWN = [
  "# Breach Dogfood Runbook",
  "",
  "<!-- dmb-playable-element:v2 kind=beat id=beat:hold-breach beat_kind=spine -->",
  "## Hold the Breach",
  "",
  "Creatures have broken through the defensive wall. The party must decide",
  "whether to pursue the surviving brood or stabilize the breach before the line",
  "fails completely.",
  "",
  "<!-- dmb-playable-element:v2 kind=scene id=scene:north-gate -->",
  "### North Gate",
  "",
  "The gate is damaged, the last creatures are retreating toward a broken tunnel,",
  "and exhausted defenders are trying to stabilize the wall.",
  "",
  "<!-- dmb-playable-element:v2 kind=choice id=choice:surviving-brood scene=scene:north-gate -->",
  "### What do they do with the surviving brood?",
  "",
  "The brood is disappearing underground while the defenders call for help at the",
  "breach.",
  "",
  "<!-- dmb-playable-element:v2 kind=option id=option:follow-brood activates=scene:tunnel-pursuit,beat:lower-tunnels -->",
  "- Follow it",
  "",
  "  The party pursues the retreating creatures into the lower tunnels before",
  "  reinforcements arrive.",
  "",
  "<!-- dmb-playable-element:v2 kind=option id=option:seal-breach suppresses=scene:tunnel-pursuit -->",
  "- Seal the breach",
  "",
  "  The immediate breach is contained, but the surviving creatures remain",
  "  somewhere below.",
  "",
  "<!-- dmb-playable-element:v2 kind=scene id=scene:tunnel-pursuit -->",
  "### Tunnel Pursuit",
  "",
  "The party enters a damaged tunnel after the fleeing creatures while loose stone",
  "and timbers shift overhead.",
  "",
  "<!-- dmb-playable-element:v2 kind=beat id=beat:lower-tunnels beat_kind=optional -->",
  "## Lower Tunnels",
  "",
  "Following the brood deeper turns the defense of the gate into a search below",
  "the fortifications.",
  "",
].join("\n");

export function breachDogfoodManifestV2(run: PlayRunRecord): PlayRunReferenceManifestV2 {
  return {
    schema_version: "dmb_play_run_reference_manifest_v2",
    run_id: run.run_id,
    playable_artifact_id: run.playable_artifact_id,
    playable_revision: run.playable_revision,
    playable_content_sha256: run.playable_content_sha256,
    sealed_at: run.created_at,
    beats: [
      { beat_id: "beat:hold-breach", beat_kind: "spine" },
      { beat_id: "beat:lower-tunnels", beat_kind: "optional" },
    ],
    scenes: [
      { scene_id: "scene:north-gate", beat_id: "beat:hold-breach" },
      { scene_id: "scene:tunnel-pursuit", beat_id: "beat:hold-breach" },
    ],
    choices: [
      {
        choice_id: "choice:surviving-brood",
        beat_id: "beat:hold-breach",
        scene_id: "scene:north-gate",
      },
    ],
    options: [
      { option_id: "option:follow-brood", choice_id: "choice:surviving-brood" },
      { option_id: "option:seal-breach", choice_id: "choice:surviving-brood" },
    ],
    edges: [
      {
        option_id: "option:follow-brood",
        effect: "activate",
        target_kind: "scene",
        target_id: "scene:tunnel-pursuit",
      },
      {
        option_id: "option:follow-brood",
        effect: "activate",
        target_kind: "beat",
        target_id: "beat:lower-tunnels",
      },
      {
        option_id: "option:seal-breach",
        effect: "suppress",
        target_kind: "scene",
        target_id: "scene:tunnel-pursuit",
      },
    ],
  };
}
