import type { UnionSupergraphProjectionResponse } from "../../api/types";

/** Minimal Session 23 projection payload aligned with backend fixture tests. */
export const session23UnionSupergraphFixture: UnionSupergraphProjectionResponse = {
  campaign_id: "longmont-c2",
  session_id: "session-23",
  graph_id: "longmont-c2:union-supergraph",
  markdown: "# Session 23 Sample\n\n[Caelynn](dmb-node:pc_caelynn) held the Mireward gate while the party tried to understand what had happened near [Mirathorn](dmb-node:loc_mirathorn).",
  focus: {
    focus_session_id: "session-23",
    focused_evidence_ref_ids: ["evidence:session-23:caelynn:recap-mention"],
    focused_edge_ids: ["edge:pc_caelynn:participated_in:event_session_23_mireward_gate"],
    focused_node_ids: ["pc_caelynn", "event_session_23_mireward_gate"],
  },
  node_views: {
    pc_caelynn: {
      node_id: "pc_caelynn",
      label: "Caelynn",
      kind: "pc",
      role: "pc",
      aliases: ["Caelynn"],
      source_domains: ["recap", "worldbuilding"],
      anchored_to_focus_session: true,
      summary: null,
      evidence_badges: [
        {
          evidence_ref_id: "evidence:session-23:caelynn:recap-mention",
          source_artifact_id: "artifact:recap:longmont-c2:session-23",
          source_domain: "recap",
          evidence_role: "focus_session_recap_mention",
          is_focus_session_evidence: true,
          can_open_source: true,
          can_highlight_span: true,
          label: "recap: focus_session_recap_mention",
        },
        {
          evidence_ref_id: "evidence:worldbuilding:caelynn:character-note",
          source_artifact_id: "artifact:worldbuilding:longmont-c2:caelynn-note",
          source_domain: "worldbuilding",
          evidence_role: "character_context",
          is_focus_session_evidence: false,
          can_open_source: true,
          can_highlight_span: false,
          label: "worldbuilding: character_context",
        },
      ],
      adjacency: [
        {
          edge_id: "edge:pc_caelynn:participated_in:event_session_23_mireward_gate",
          node_id: "event_session_23_mireward_gate",
          label: "Mireward Gate Incident",
          kind: "event",
          predicate: "participated_in",
          direction: "outbound",
          anchored_to_focus_session: true,
          source_domains: ["recap"],
          evidence_ref_ids: ["evidence:session-23:caelynn:recap-mention"],
        },
        {
          edge_id: "edge:pc_caelynn:connected_to:loc_mirathorn",
          node_id: "loc_mirathorn",
          label: "Mirathorn",
          kind: "location",
          predicate: "connected_to",
          direction: "outbound",
          anchored_to_focus_session: false,
          source_domains: ["worldbuilding"],
          evidence_ref_ids: ["evidence:worldbuilding:caelynn:character-note"],
        },
      ],
    },
    event_session_23_mireward_gate: {
      node_id: "event_session_23_mireward_gate",
      label: "Mireward Gate Incident",
      kind: "event",
      role: "event",
      aliases: ["Mireward gate"],
      source_domains: ["recap"],
      anchored_to_focus_session: true,
      summary: null,
      evidence_badges: [],
      adjacency: [],
    },
    loc_mirathorn: {
      node_id: "loc_mirathorn",
      label: "Mirathorn",
      kind: "location",
      role: "location",
      aliases: ["Mirathorn"],
      source_domains: ["worldbuilding"],
      anchored_to_focus_session: false,
      summary: null,
      evidence_badges: [],
      adjacency: [],
    },
  },
  mentions: [
    {
      mention_id: "mention:pc_caelynn:20",
      node_id: "pc_caelynn",
      label: "Caelynn",
      start_offset: 20,
      end_offset: 27,
      evidence_ref_ids: ["evidence:session-23:caelynn:recap-mention"],
    },
  ],
};
