import {
  Callout,
  Card,
  CardBody,
  CardHeader,
  Code,
  Divider,
  H1,
  H2,
  Pill,
  Stack,
  Text,
} from 'cursor/canvas';

const sourceRecap =
  'corpus/eldyrwild-markdown/Longmont Campaign/Campaign 1/Session Recaps/Session 2 - Finishing the Job.md';

const breadcrumbArtifact =
  'evals/sentence_routing_retrieval_falsification/manual_labels/Session 2 - Finishing the Job.breadcrumbed.md';

const candidateArtifact =
  'evals/sentence_routing_retrieval_falsification/artifacts/runs/2026-05-05/c1s2_query_candidates.json';

type CandidateRow = {
  readonly candidate_id: string;
  readonly category: string;
  readonly question: string;
  readonly expected_answer_draft: string;
  readonly must_hit_tokens_draft: readonly string[];
  readonly supporting_unit_ids: readonly string[];
  readonly supporting_route_substrings: readonly string[];
  readonly supporting_evidence_snippets: readonly string[];
  readonly notes: string;
  readonly review_status: string;
};

// BEGIN GENERATED C1S2_CANDIDATE_DETAIL
// Generated by c1s2_query_candidate_canvas_emit.py — do not hand-edit.
const c1s2CandidateCanvasGenerated = {
  "c1s2CandidateSummaryGenerated": {
    "schema": "dmb_breadcrumb_query_candidates_v1",
    "source_breadcrumb_path": "evals/sentence_routing_retrieval_falsification/manual_labels/Session 2 - Finishing the Job.breadcrumbed.md",
    "campaign_id": "longmont-c1",
    "session_number": 2,
    "generated_at_utc": "20260505T172229Z",
    "candidate_count": 12
  },
  "c1s2CandidateRowsGenerated": [
    {
      "candidate_id": "c1s2_cand_u_L0003_01",
      "category": "relationship_or_faction_context",
      "question": "Remind me how the crew came out of the tower-basement mess overall.",
      "expected_answer_draft": "The gang survived, they kinda even thrived.",
      "must_hit_tokens_draft": [
        "The"
      ],
      "supporting_unit_ids": [
        "u-L0003-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Parties/party_merchant_guards"
      ],
      "supporting_evidence_snippets": [
        "The gang survived, they kinda even thrived."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0003_02",
      "category": "mechanical_prep_context",
      "question": "What were the weird basement threats again, and how scary did they feel compared to the rats?",
      "expected_answer_draft": "Compared to the rats, the Giant Flaming Spider, the Giant Centipede that crawled out of the well, and the rat that absolutely was NOT about to mutate were no big deal.",
      "must_hit_tokens_draft": [
        "Compared",
        "Giant Flaming Spider",
        "Giant Centipede",
        "rats",
        "spider",
        "centipede"
      ],
      "supporting_unit_ids": [
        "u-L0003-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/magma_spider",
        "Campaign 1/NPCs/giant_centipede_well"
      ],
      "supporting_evidence_snippets": [
        "Compared to the rats, the Giant Flaming Spider, the Giant Centipede that crawled out of the well, and the rat that absolutely was NOT about to mutate were no big deal."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0005_01",
      "category": "event_context",
      "question": "After they finished clearing the wizard tower basement, what was the broad outcome for the party?",
      "expected_answer_draft": "After clearing the rest of the wizards tower basement they came away richly rewarded.",
      "must_hit_tokens_draft": [
        "After"
      ],
      "supporting_unit_ids": [
        "u-L0005-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/wizards_tower_brewing_company"
      ],
      "supporting_evidence_snippets": [
        "After clearing the rest of the wizards tower basement they came away richly rewarded."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0005_02",
      "category": "event_context",
      "question": "What loot and strange alchemy-room stuff did they actually uncover down there?",
      "expected_answer_draft": "Finding a sack of gems, some mystery potions on corpses in the well, and perhaps most importantly bashing down a wall to reveal a room full of healing potions and alchemical tools and ingredients of and ancient and incredible design.",
      "must_hit_tokens_draft": [
        "Finding",
        "gems",
        "potions"
      ],
      "supporting_unit_ids": [
        "u-L0005-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/wizards_tower_brewing_company"
      ],
      "supporting_evidence_snippets": [
        "Finding a sack of gems, some mystery potions on corpses in the well, and perhaps most importantly bashing down a wall to reveal a room full of healing potions and alchemical tools and ingredients of and ancient and incredible design."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0005_03",
      "category": "core_recall",
      "question": "Did the party know what to do with those ancient alchemy tools yet, or was it just cool treasure for now?",
      "expected_answer_draft": "They unfortunately haven't the first clue how to use them, but they are cool!",
      "must_hit_tokens_draft": [
        "They"
      ],
      "supporting_unit_ids": [
        "u-L0005-03"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "They unfortunately haven't the first clue how to use them, but they are cool!"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0007_01",
      "category": "event_context",
      "question": "What deal did they work out with Glowkindle once the original rat job had gone wildly off-script?",
      "expected_answer_draft": "Since this room was not part of the original contract, and really neither was the rest of this god forsaken place, they negotiated with Glowkindle for the right to stash gear in the hidden alchemy room.",
      "must_hit_tokens_draft": [
        "Since",
        "Glowkindle"
      ],
      "supporting_unit_ids": [
        "u-L0007-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/glowkindle"
      ],
      "supporting_evidence_snippets": [
        "Since this room was not part of the original contract, and really neither was the rest of this god forsaken place, they negotiated with Glowkindle for the right to stash gear in the hidden alchemy room."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0007_02",
      "category": "core_recall",
      "question": "What was the vibe on that hidden-room arrangement: a real foothold, or just the first tiny step?",
      "expected_answer_draft": "It's not much but it's a start.",
      "must_hit_tokens_draft": [],
      "supporting_unit_ids": [
        "u-L0007-02"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "It's not much but it's a start."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0009_01",
      "category": "relationship_or_faction_context",
      "question": "Where did the party land after the job: pay, lessons learned, and are they sticking together?",
      "expected_answer_draft": "After making pretty good money, 25 gp each, a bit of loot, and learning a lot about the dangers of clearing rats out of basements, the group decided to stick together and see where the winds take them.",
      "must_hit_tokens_draft": [
        "25 gp",
        "After",
        "rats"
      ],
      "supporting_unit_ids": [
        "u-L0009-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Parties/party_merchant_guards"
      ],
      "supporting_evidence_snippets": [
        "After making pretty good money, 25 gp each, a bit of loot, and learning a lot about the dangers of clearing rats out of basements, the group decided to stick together and see where the winds take them."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0011_01",
      "category": "consequence_or_hook_context",
      "question": "What obvious next-job hook is sitting there with Glowkindle?",
      "expected_answer_draft": "Will they ask Glowkindle for more work?",
      "must_hit_tokens_draft": [
        "Will",
        "Glowkindle"
      ],
      "supporting_unit_ids": [
        "u-L0011-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/glowkindle",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Will they ask Glowkindle for more work?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0011_02",
      "category": "consequence_or_hook_context",
      "question": "If they head back toward Stonebridge, who and where might they naturally check in with?",
      "expected_answer_draft": "Will they had back to Stonebridge to say hi to Grishna at the River's Edge Pub?",
      "must_hit_tokens_draft": [
        "Will",
        "Stonebridge",
        "Grishna",
        "River",
        "Edge Pub"
      ],
      "supporting_unit_ids": [
        "u-L0011-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/NPCs/grishna",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/Locations/wizards_tower_brewing_company"
      ],
      "supporting_evidence_snippets": [
        "Will they had back to Stonebridge to say hi to Grishna at the River's Edge Pub?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0011_03",
      "category": "consequence_or_hook_context",
      "question": "What Wizard's Tower question does the recap tee up, without answering it yet?",
      "expected_answer_draft": "Will they follow up on the errant thought of what if there is more to the Wizard's Tower?",
      "must_hit_tokens_draft": [
        "Will",
        "Wizard",
        "Tower"
      ],
      "supporting_unit_ids": [
        "u-L0011-03"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/wizards_tower_brewing_company"
      ],
      "supporting_evidence_snippets": [
        "Will they follow up on the errant thought of what if there is more to the Wizard's Tower?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s2_cand_u_L0013_01",
      "category": "consequence_or_hook_context",
      "question": "How does the recap leave the table hanging at the end?",
      "expected_answer_draft": "Stay tuned!",
      "must_hit_tokens_draft": [
        "Stay"
      ],
      "supporting_unit_ids": [
        "u-L0013-01"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "Stay tuned!"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    }
  ]
} as const;
// END GENERATED C1S2_CANDIDATE_DETAIL

function CandidateCard({ row }: { row: CandidateRow }) {
  return (
    <Card key={row.candidate_id}>
      <CardHeader>
        <Stack gap={6}>
          <Text size="large" weight="semibold">
            {row.candidate_id}
          </Text>
          <Stack direction="horizontal" gap={6}>
            <Pill tone="info">{row.category}</Pill>
            <Pill tone={row.review_status === 'accept' ? 'success' : 'neutral'}>{row.review_status}</Pill>
          </Stack>
        </Stack>
      </CardHeader>
      <CardBody>
        <Stack gap={8}>
          <Text weight="semibold">Draft question</Text>
          <Text tone="secondary">{row.question}</Text>
          <Text weight="semibold">Expected answer (draft)</Text>
          <Text tone="secondary">{row.expected_answer_draft}</Text>
          <Text weight="semibold">Must-hit tokens (draft)</Text>
          <Text tone="secondary">{row.must_hit_tokens_draft.join(', ') || '—'}</Text>
          <Text weight="semibold">Routes (draft needles)</Text>
          <Text tone="secondary">
            {row.supporting_route_substrings.join(' · ') || '—'}
          </Text>
          <Text weight="semibold">Evidence snippet</Text>
          <Text tone="secondary">{row.supporting_evidence_snippets[0] ?? '—'}</Text>
          <Text size="small" tone="secondary">
            {row.notes}
          </Text>
        </Stack>
      </CardBody>
    </Card>
  );
}

export default function C1S2BreadcrumbQueryCandidateReviewCanvas() {
  const summary = c1s2CandidateCanvasGenerated.c1s2CandidateSummaryGenerated;
  const rows = c1s2CandidateCanvasGenerated.c1s2CandidateRowsGenerated as unknown as readonly CandidateRow[];
  const hasRows = rows.length > 0;

  return (
    <Stack gap={16} padding={16}>
      <H1>C1S2 — Breadcrumb query candidates</H1>
      <Text tone="secondary">
        Component-shaped review surface: one card per generated candidate. Promote accepted rows into{' '}
        <Code>gold/breadcrumb_query_natural_c1s2_v1.json</Code> after rewriting questions into natural GM phrasing.
      </Text>
      <Stack gap={4}>
        <Text>
          <strong>Source recap:</strong> <Code>{sourceRecap}</Code>
        </Text>
        <Text>
          <strong>Breadcrumb index:</strong> <Code>{breadcrumbArtifact}</Code>
        </Text>
        <Text>
          <strong>Candidate artifact:</strong> <Code>{candidateArtifact}</Code>
        </Text>
      </Stack>
      <Callout tone="info" title="Regenerate">
        <Text>
          <Code>uv run python -m evals.sentence_routing_retrieval_falsification.c1s2_query_candidate_build</Code>
          <br />
          <Code>uv run python -m evals.sentence_routing_retrieval_falsification.c1s2_query_candidate_canvas_emit --candidates {candidateArtifact} --canvas-tsx ~/.cursor/projects/.../canvases/c1s2-breadcrumb-query-candidate-review.canvas.tsx</Code>
        </Text>
      </Callout>
      <Divider />
      {hasRows ? (
        <>
          <H2>
            Candidates ({summary.candidate_count}) — session {summary.session_number}
          </H2>
          <Stack gap={10}>
            {rows.map((row) => (
              <CandidateCard key={row.candidate_id} row={row} />
            ))}
          </Stack>
        </>
      ) : (
        <Callout tone="warning" title="Generated block is empty">
          <Text>Run the candidate builder + emitter (see above).</Text>
        </Callout>
      )}
    </Stack>
  );
}
