import {
  Callout,
  Card,
  CardBody,
  CardHeader,
  Code,
  Divider,
  H1,
  H2,
  Pill,
  Stack,
  Text,
} from 'cursor/canvas';

const sourceRecap =
  'corpus/eldyrwild-markdown/Longmont Campaign/Campaign 1/Session Recaps/Session 3 - The Stone Bridge Flood.md';

const breadcrumbArtifact =
  'evals/sentence_routing_retrieval_falsification/manual_labels/Session 3 - The Stone Bridge Flood.breadcrumbed.md';

const candidateArtifact =
  'evals/sentence_routing_retrieval_falsification/artifacts/runs/2026-05-05/c1s3_query_candidates.json';

type CandidateRow = {
  readonly candidate_id: string;
  readonly category: string;
  readonly question: string;
  readonly expected_answer_draft: string;
  readonly must_hit_tokens_draft: readonly string[];
  readonly supporting_unit_ids: readonly string[];
  readonly supporting_route_substrings: readonly string[];
  readonly supporting_evidence_snippets: readonly string[];
  readonly notes: string;
  readonly review_status: string;
};

// BEGIN GENERATED C1S3_CANDIDATE_DETAIL
// Generated by c1s3_query_candidate_canvas_emit.py — do not hand-edit.
const c1s3CandidateCanvasGenerated = {
  "c1s3CandidateSummaryGenerated": {
    "schema": "dmb_breadcrumb_query_candidates_v1",
    "source_breadcrumb_path": "evals/sentence_routing_retrieval_falsification/manual_labels/Session 3 - The Stone Bridge Flood.breadcrumbed.md",
    "campaign_id": "longmont-c1",
    "session_number": 3,
    "generated_at_utc": "20260505T185231Z",
    "candidate_count": 60
  },
  "c1s3CandidateRowsGenerated": [
    {
      "candidate_id": "c1s3_cand_u_L0003_01",
      "category": "entity_context",
      "question": "What was the table hook going into this session \u2014 artifact rumor and celebration?",
      "expected_answer_draft": "Adventure hook, hear about a mysterious artifact while celebrating.",
      "must_hit_tokens_draft": [
        "Adventure"
      ],
      "supporting_unit_ids": [
        "u-L0003-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Adventure hook, hear about a mysterious artifact while celebrating."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0004_01",
      "category": "location_context",
      "question": "What kind of environmental problem did the rain turn into at the table?",
      "expected_answer_draft": "Unseasonable torrential rains floods wherever the players are, non combat problem solving.",
      "must_hit_tokens_draft": [
        "Unseasonable"
      ],
      "supporting_unit_ids": [
        "u-L0004-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Unseasonable torrential rains floods wherever the players are, non combat problem solving."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0004_02",
      "category": "entity_context",
      "question": "Besides staying alive themselves, what pressure did the recap put on the party?",
      "expected_answer_draft": "They have to keep themselves alive, and save townsfolk.",
      "must_hit_tokens_draft": [
        "They"
      ],
      "supporting_unit_ids": [
        "u-L0004-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "They have to keep themselves alive, and save townsfolk."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0006_01",
      "category": "entity_context",
      "question": "What was the GM's 'big beats' spine for Session 3?",
      "expected_answer_draft": "Big beats :",
      "must_hit_tokens_draft": [
        "Big"
      ],
      "supporting_unit_ids": [
        "u-L0006-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Big beats :"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0008_01",
      "category": "entity_context",
      "question": "Who did we ride with early on, and what goat did the table fall for?",
      "expected_answer_draft": "Rode with Pippa and fell in love with Bubbles.",
      "must_hit_tokens_draft": [
        "Rode",
        "Pippa",
        "Bubbles"
      ],
      "supporting_unit_ids": [
        "u-L0008-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Rode with Pippa and fell in love with Bubbles."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0010_01",
      "category": "location_context",
      "question": "Who helped with debris from the broken upriver structure?",
      "expected_answer_draft": "Helped Kirfan pull up debris from the broken structure from upriver.",
      "must_hit_tokens_draft": [
        "Helped Kirfan",
        "Kirfan"
      ],
      "supporting_unit_ids": [
        "u-L0010-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/kirfan"
      ],
      "supporting_evidence_snippets": [
        "Helped Kirfan pull up debris from the broken structure from upriver."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0010_02",
      "category": "location_context",
      "question": "What naming TBD did the recap call out for the river/upriver town?",
      "expected_answer_draft": "(River and Upriver town need a name)",
      "must_hit_tokens_draft": [
        "River",
        "Upriver"
      ],
      "supporting_unit_ids": [
        "u-L0010-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/grishna"
      ],
      "supporting_evidence_snippets": [
        "(River and Upriver town need a name)"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0012_01",
      "category": "entity_context",
      "question": "Who comped beer and board after the helpful work?",
      "expected_answer_draft": "Got comp'd beer and board from Grishna.",
      "must_hit_tokens_draft": [
        "Got",
        "Grishna"
      ],
      "supporting_unit_ids": [
        "u-L0012-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/grishna"
      ],
      "supporting_evidence_snippets": [
        "Got comp'd beer and board from Grishna."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0014_01",
      "category": "location_context",
      "question": "What did Stafl do at the pub that sold the Wizard's Tower Brewery story?",
      "expected_answer_draft": "Stafl wrote and played an incredible song that woo'd the town in the retelling of the Wizard's Tower Brewery adventure.",
      "must_hit_tokens_draft": [
        "Stafl",
        "Wizard",
        "Tower Brewery"
      ],
      "supporting_unit_ids": [
        "u-L0014-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/stafl",
        "Campaign 1/Locations/wizards_tower_brewing_company"
      ],
      "supporting_evidence_snippets": [
        "Stafl wrote and played an incredible song that woo'd the town in the retelling of the Wizard's Tower Brewery adventure."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0016_01",
      "category": "location_context",
      "question": "How did the weather escalate before the real crisis?",
      "expected_answer_draft": "Horrible storm kicks up and gets worse.",
      "must_hit_tokens_draft": [
        "Horrible"
      ],
      "supporting_unit_ids": [
        "u-L0016-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Horrible storm kicks up and gets worse."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0018_01",
      "category": "entity_context",
      "question": "What kicked the party out the door when Pippa started yelling?",
      "expected_answer_draft": "Players heard Pippa yelling and immediately ran out to help find Bubbles.",
      "must_hit_tokens_draft": [
        "Players",
        "Pippa",
        "Bubbles"
      ],
      "supporting_unit_ids": [
        "u-L0018-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Players heard Pippa yelling and immediately ran out to help find Bubbles."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0020_01",
      "category": "mechanical_prep_context",
      "question": "How did Ephanna first try to reach Bubbles on the rock?",
      "expected_answer_draft": "Ephanna uses mage hand to lasso Bubbles on the rock.",
      "must_hit_tokens_draft": [
        "Ephanna",
        "Bubbles",
        "mage hand"
      ],
      "supporting_unit_ids": [
        "u-L0020-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Ephanna uses mage hand to lasso Bubbles on the rock."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0020_02",
      "category": "mechanical_prep_context",
      "question": "What went wrong when Bubbles panicked on that first mage-hand attempt?",
      "expected_answer_draft": "Bubbles is too panicked and bites the mage hand.",
      "must_hit_tokens_draft": [
        "Bubbles",
        "mage hand"
      ],
      "supporting_unit_ids": [
        "u-L0020-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/caelynn"
      ],
      "supporting_evidence_snippets": [
        "Bubbles is too panicked and bites the mage hand."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0022_01",
      "category": "mechanical_prep_context",
      "question": "What did Caelynn do to give people footing around Bubble's rock?",
      "expected_answer_draft": "Caelynn uses ice to freeze the base of the rock and make a platform.",
      "must_hit_tokens_draft": [
        "Caelynn"
      ],
      "supporting_unit_ids": [
        "u-L0022-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/caelynn"
      ],
      "supporting_evidence_snippets": [
        "Caelynn uses ice to freeze the base of the rock and make a platform."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0024_01",
      "category": "core_recall",
      "question": "Who went in the water and who lost the rope on the first dive beat?",
      "expected_answer_draft": "Bonogo dives in the water, Baergrom loses the rope.",
      "must_hit_tokens_draft": [
        "Bonogo",
        "Baergrom"
      ],
      "supporting_unit_ids": [
        "u-L0024-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom"
      ],
      "supporting_evidence_snippets": [
        "Bonogo dives in the water, Baergrom loses the rope."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0026_01",
      "category": "location_context",
      "question": "Where did Bonogo end up once the river carried him off?",
      "expected_answer_draft": "Bonogo flows downstream and has a wonderful zen underwater adventure.",
      "must_hit_tokens_draft": [
        "Bonogo"
      ],
      "supporting_unit_ids": [
        "u-L0026-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/bonogo",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Bonogo flows downstream and has a wonderful zen underwater adventure."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0028_01",
      "category": "location_context",
      "question": "How did Stafl use the town once nets became part of the plan?",
      "expected_answer_draft": "Stafl gathers town support, nets are dropped across the bridge flow ways.",
      "must_hit_tokens_draft": [
        "Stafl"
      ],
      "supporting_unit_ids": [
        "u-L0028-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/stafl",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Stafl gathers town support, nets are dropped across the bridge flow ways."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0030_01",
      "category": "mechanical_prep_context",
      "question": "When did Ephanna's mage hand finally stick the landing with Bubbles?",
      "expected_answer_draft": "Ephanna's mage hand succeeds the second time and lassos Bubbles, lead her to Ephanna.",
      "must_hit_tokens_draft": [
        "Ephanna",
        "Bubbles",
        "mage hand"
      ],
      "supporting_unit_ids": [
        "u-L0030-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Ephanna's mage hand succeeds the second time and lassos Bubbles, lead her to Ephanna."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0032_01",
      "category": "mechanical_prep_context",
      "question": "What did Karsemine do right after the comma-beat 'Zephyr strike' line in the outline?",
      "expected_answer_draft": "Karsemine uses Zephyr strike,",
      "must_hit_tokens_draft": [
        "Karsemine",
        "Zephyr"
      ],
      "supporting_unit_ids": [
        "u-L0032-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine"
      ],
      "supporting_evidence_snippets": [
        "Karsemine uses Zephyr strike,"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0034_01",
      "category": "location_context",
      "question": "How did the party actually get to StoneBridge with Pippa, Bubbles, and the kegs?",
      "expected_answer_draft": "Ready for some rest, ready to not be covered in the sweat and ichor of the day, Caelynn, Karsemine, Stafl, Baergrom, and Ephanna accepted the offer of a ride to StoneBridge with Pippa.",
      "must_hit_tokens_draft": [
        "Ready",
        "Caelynn",
        "Karsemine",
        "Stafl",
        "Baergrom",
        "Ephanna",
        "Pippa",
        "StoneBridge"
      ],
      "supporting_unit_ids": [
        "u-L0034-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo"
      ],
      "supporting_evidence_snippets": [
        "Ready for some rest, ready to not be covered in the sweat and ichor of the day, Caelynn, Karsemine, Stafl, Baergrom, and Ephanna accepted the offer of a ride to StoneBridge with Pippa."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0034_02",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Pippa a bright and talkative Gnome obsessed with crafting and understanding beer, hitched up Bubbles the Float Goat to her wagon full of kegs and led the crew to a dock and barge on the river.",
      "must_hit_tokens_draft": [
        "Pippa",
        "Gnome",
        "Bubbles",
        "Float Goat"
      ],
      "supporting_unit_ids": [
        "u-L0034-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/NPCs/grishna",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/stafl"
      ],
      "supporting_evidence_snippets": [
        "Pippa a bright and talkative Gnome obsessed with crafting and understanding beer, hitched up Bubbles the Float Goat to her wagon full of kegs and led the crew to a dock and barge on the river."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0034_03",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Along the way down river, they encountered an elderly fisherman, whose net was stuck.",
      "must_hit_tokens_draft": [
        "Along"
      ],
      "supporting_unit_ids": [
        "u-L0034-03"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/NPCs/grishna",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/stafl"
      ],
      "supporting_evidence_snippets": [
        "Along the way down river, they encountered an elderly fisherman, whose net was stuck."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0034_04",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Without missing a beat Bonogo out of selflessness and hopes for a giant fish to eat, dove into the water to find the damned net didn't have a fish, stupid useless net.",
      "must_hit_tokens_draft": [
        "Without",
        "Bonogo"
      ],
      "supporting_unit_ids": [
        "u-L0034-04"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/NPCs/grishna",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/stafl"
      ],
      "supporting_evidence_snippets": [
        "Without missing a beat Bonogo out of selflessness and hopes for a giant fish to eat, dove into the water to find the damned net didn't have a fish, stupid useless net."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0034_05",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "With some trial and error and stradling of boats Stafl and Baergrom I think pulled the net to surface to see it looked to be the corner beams of a roof.",
      "must_hit_tokens_draft": [
        "With",
        "Stafl",
        "Baergrom"
      ],
      "supporting_unit_ids": [
        "u-L0034-05"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/NPCs/grishna",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/stafl"
      ],
      "supporting_evidence_snippets": [
        "With some trial and error and stradling of boats Stafl and Baergrom I think pulled the net to surface to see it looked to be the corner beams of a roof."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0036_01",
      "category": "location_context",
      "question": "Walk me through arriving at StoneBridge, the pub, the storm, and the moment Pippa bolts for Bubbles.",
      "expected_answer_draft": "Once at StoneBridge and unloading beer, it became clear a storm was coming.",
      "must_hit_tokens_draft": [
        "Once",
        "StoneBridge"
      ],
      "supporting_unit_ids": [
        "u-L0036-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/NPCs/grishna",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/stafl"
      ],
      "supporting_evidence_snippets": [
        "Once at StoneBridge and unloading beer, it became clear a storm was coming."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0036_02",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Hitching up Bubbles and the barge, into the River's Edge Pub for a welcome round of beers and some bragging to Grishna about their adventures.",
      "must_hit_tokens_draft": [
        "Hitching",
        "Bubbles",
        "River",
        "Edge Pub",
        "Grishna"
      ],
      "supporting_unit_ids": [
        "u-L0036-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Hitching up Bubbles and the barge, into the River's Edge Pub for a welcome round of beers and some bragging to Grishna about their adventures."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0036_03",
      "category": "entity_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Inside was the evening crew, Grishna, patrons, and another bard!",
      "must_hit_tokens_draft": [
        "Inside",
        "Grishna"
      ],
      "supporting_unit_ids": [
        "u-L0036-03"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Inside was the evening crew, Grishna, patrons, and another bard!"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0036_04",
      "category": "entity_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Who Stafl immediately joined in a jam with that undoubtedly demonstrated his superior song craft and bardic talents.",
      "must_hit_tokens_draft": [
        "Who Stafl",
        "Stafl"
      ],
      "supporting_unit_ids": [
        "u-L0036-04"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Who Stafl immediately joined in a jam with that undoubtedly demonstrated his superior song craft and bardic talents."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0036_05",
      "category": "entity_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "After some excellent drinks and music, Pippa realizes the loud drumming isn't just the bard, but a torrent of rain on the roof excuses herself to check on Bubbles.",
      "must_hit_tokens_draft": [
        "After",
        "Pippa",
        "Bubbles"
      ],
      "supporting_unit_ids": [
        "u-L0036-05"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "After some excellent drinks and music, Pippa realizes the loud drumming isn't just the bard, but a torrent of rain on the roof excuses herself to check on Bubbles."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0036_06",
      "category": "entity_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Gone for a few moments, during a pause in the retelling of the day's events, weeping is heard from another table, followed by a piercing yell in between cascades of rain off the roof.",
      "must_hit_tokens_draft": [
        "Gone"
      ],
      "supporting_unit_ids": [
        "u-L0036-06"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "Gone for a few moments, during a pause in the retelling of the day's events, weeping is heard from another table, followed by a piercing yell in between cascades of rain off the roof."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0038_01",
      "category": "entity_context",
      "question": "What was the yell that cut through the rain?",
      "expected_answer_draft": "\"BUBBLES!\"",
      "must_hit_tokens_draft": [
        "Bubbles"
      ],
      "supporting_unit_ids": [
        "u-L0038-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat"
      ],
      "supporting_evidence_snippets": [
        "\"BUBBLES!\""
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_01",
      "category": "location_context",
      "question": "When we rush outside, what is Pippa doing and what's wrong with her dialog beat?",
      "expected_answer_draft": "Dropping everything and rushing outside, you found Pippa, soaked and panicked.",
      "must_hit_tokens_draft": [
        "Dropping",
        "Pippa"
      ],
      "supporting_unit_ids": [
        "u-L0040-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Dropping everything and rushing outside, you found Pippa, soaked and panicked."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_02",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Gripping onto the front of the pub holding on in rushing water up to her waste.",
      "must_hit_tokens_draft": [
        "Gripping"
      ],
      "supporting_unit_ids": [
        "u-L0040-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Gripping onto the front of the pub holding on in rushing water up to her waste."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_03",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "\"Help!",
      "must_hit_tokens_draft": [
        "Help"
      ],
      "supporting_unit_ids": [
        "u-L0040-03"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "\"Help!"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_04",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "I can't find Pippa\" she babbles about a broken lead.",
      "must_hit_tokens_draft": [
        "Pippa"
      ],
      "supporting_unit_ids": [
        "u-L0040-04"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "I can't find Pippa\" she babbles about a broken lead."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_05",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Rapidly searching around Bubbles is found wildly bleating on a rock in the river.",
      "must_hit_tokens_draft": [
        "Rapidly",
        "Bubbles"
      ],
      "supporting_unit_ids": [
        "u-L0040-05"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Rapidly searching around Bubbles is found wildly bleating on a rock in the river."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_06",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Out on a rickety dock, shaking in the flood and downpour, the river frothing, rapids crashing all around as it wildly rushed.",
      "must_hit_tokens_draft": [
        "Out"
      ],
      "supporting_unit_ids": [
        "u-L0040-06"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Out on a rickety dock, shaking in the flood and downpour, the river frothing, rapids crashing all around as it wildly rushed."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_07",
      "category": "mechanical_prep_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "a lasso was made and handed to a mage hand Ephanna created.",
      "must_hit_tokens_draft": [
        "Ephanna",
        "mage hand"
      ],
      "supporting_unit_ids": [
        "u-L0040-07"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "a lasso was made and handed to a mage hand Ephanna created."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_08",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Stafl runs for help, and gathers townfolk to set nets across the river.",
      "must_hit_tokens_draft": [
        "Stafl"
      ],
      "supporting_unit_ids": [
        "u-L0040-08"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Stafl runs for help, and gathers townfolk to set nets across the river."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_09",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Bonogo and Baergrom prepare for Bonogo to dive in.",
      "must_hit_tokens_draft": [
        "Bonogo",
        "Baergrom"
      ],
      "supporting_unit_ids": [
        "u-L0040-09"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Bonogo and Baergrom prepare for Bonogo to dive in."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_10",
      "category": "mechanical_prep_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Caelynn desperately fires ice bolts to freeze a platform around Bubble's rock.",
      "must_hit_tokens_draft": [
        "Caelynn",
        "Bubble"
      ],
      "supporting_unit_ids": [
        "u-L0040-10"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Caelynn desperately fires ice bolts to freeze a platform around Bubble's rock."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0040_11",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Stafl began banging on doors and assisting townfolk escape the flood and gather at the pub on high ground.",
      "must_hit_tokens_draft": [
        "Stafl"
      ],
      "supporting_unit_ids": [
        "u-L0040-11"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Stafl began banging on doors and assisting townfolk escape the flood and gather at the pub on high ground."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0041_01",
      "category": "mechanical_prep_context",
      "question": "What happens on the second mage-hand attempt when Bubbles bites and the rope drops?",
      "expected_answer_draft": "Sending the mage hand and rope out to Bubbles, the Float Goat panics and bites, destroying the mage hand and dropping the rope into the water.",
      "must_hit_tokens_draft": [
        "Sending",
        "Bubbles",
        "Float Goat",
        "mage hand"
      ],
      "supporting_unit_ids": [
        "u-L0041-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/PCs/bonogo",
        "Campaign 1/PCs/baergrom",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Sending the mage hand and rope out to Bubbles, the Float Goat panics and bites, destroying the mage hand and dropping the rope into the water."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0041_02",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Desperate to save (maybe to eat, raw?",
      "must_hit_tokens_draft": [
        "Desperate"
      ],
      "supporting_unit_ids": [
        "u-L0041-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Desperate to save (maybe to eat, raw?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0041_03",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Or maybe in a curry?",
      "must_hit_tokens_draft": [],
      "supporting_unit_ids": [
        "u-L0041-03"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Or maybe in a curry?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0041_04",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Thoroughly fermented) Bonogo dives into the river with full trust in Baergrom to hold the rope, which is immediately torn out of Baergrom's hand.",
      "must_hit_tokens_draft": [
        "Thoroughly",
        "Bonogo",
        "Baergrom"
      ],
      "supporting_unit_ids": [
        "u-L0041-04"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Thoroughly fermented) Bonogo dives into the river with full trust in Baergrom to hold the rope, which is immediately torn out of Baergrom's hand."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0041_05",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Unprepared for the speed with which the river carries Bonogo away, the rope and Bonogo are gone.",
      "must_hit_tokens_draft": [
        "Unprepared",
        "Bonogo"
      ],
      "supporting_unit_ids": [
        "u-L0041-05"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "Unprepared for the speed with which the river carries Bonogo away, the rope and Bonogo are gone."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0041_06",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "The only remenant, the end of the rope whipping across the top of the river, vanishing out of sight.",
      "must_hit_tokens_draft": [
        "The"
      ],
      "supporting_unit_ids": [
        "u-L0041-06"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "The only remenant, the end of the rope whipping across the top of the river, vanishing out of sight."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0043_01",
      "category": "mechanical_prep_context",
      "question": "How does Karsemine, Stafl, Caelynn, and Ephanna converge once Bonogo and the boats are gone?",
      "expected_answer_draft": "In the face of a rapidly deteriorating situation, Karsemine cast Zephyr strike and ran down the bank, shooting arrows at wear Bonogo probably was.",
      "must_hit_tokens_draft": [
        "Karsemine",
        "Zephyr",
        "Bonogo"
      ],
      "supporting_unit_ids": [
        "u-L0043-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/karsemine",
        "Campaign 1/PCs/stafl",
        "Campaign 1/PCs/caelynn",
        "Campaign 1/PCs/ephanna",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/Locations/stonebridge"
      ],
      "supporting_evidence_snippets": [
        "In the face of a rapidly deteriorating situation, Karsemine cast Zephyr strike and ran down the bank, shooting arrows at wear Bonogo probably was."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0043_02",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Stafl and Caelynn cut loose a dinghy and let the river take them after Bonogo, with only a net with light cast on it and hope.",
      "must_hit_tokens_draft": [
        "Stafl",
        "Caelynn",
        "Bonogo"
      ],
      "supporting_unit_ids": [
        "u-L0043-02"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/bonogo",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/Locations/mirathorn"
      ],
      "supporting_evidence_snippets": [
        "Stafl and Caelynn cut loose a dinghy and let the river take them after Bonogo, with only a net with light cast on it and hope."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0043_03",
      "category": "mechanical_prep_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Ephanna and the mage hand coaxed Bubbles to the lasso and were able to get her to the dock across the ice path and rushing river.",
      "must_hit_tokens_draft": [
        "Ephanna",
        "Bubbles",
        "mage hand"
      ],
      "supporting_unit_ids": [
        "u-L0043-03"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/bonogo",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/Locations/mirathorn"
      ],
      "supporting_evidence_snippets": [
        "Ephanna and the mage hand coaxed Bubbles to the lasso and were able to get her to the dock across the ice path and rushing river."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0043_04",
      "category": "location_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Where Ephanna hopped on Bubbles back and followed after the runaway boats.",
      "must_hit_tokens_draft": [
        "Where Ephanna",
        "Bubbles",
        "Ephanna"
      ],
      "supporting_unit_ids": [
        "u-L0043-04"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/bonogo",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/Locations/mirathorn"
      ],
      "supporting_evidence_snippets": [
        "Where Ephanna hopped on Bubbles back and followed after the runaway boats."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_01",
      "category": "location_context",
      "question": "How does the session land: rescue, pub, sleep, and what 'what now' hooks does it tee up?",
      "expected_answer_draft": "Bonogo was rescued, the wet adventurers headed to the Pub to find a damp, but generally relieved, safe, and drying town.",
      "must_hit_tokens_draft": [
        "Bonogo",
        "Pub"
      ],
      "supporting_unit_ids": [
        "u-L0045-01"
      ],
      "supporting_route_substrings": [
        "Campaign 1/PCs/bonogo",
        "Campaign 1/Locations/rivers_edge_pub",
        "Campaign 1/Locations/stonebridge",
        "Campaign 1/NPCs/bubbles_the_float_goat",
        "Campaign 1/NPCs/pippa",
        "Campaign 1/Locations/mirathorn"
      ],
      "supporting_evidence_snippets": [
        "Bonogo was rescued, the wet adventurers headed to the Pub to find a damp, but generally relieved, safe, and drying town."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_02",
      "category": "core_recall",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Collapsing to sleep, they woke up the next day with the most important question of all.",
      "must_hit_tokens_draft": [
        "Collapsing"
      ],
      "supporting_unit_ids": [
        "u-L0045-02"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "Collapsing to sleep, they woke up the next day with the most important question of all."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_03",
      "category": "consequence_or_hook_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "What now?",
      "must_hit_tokens_draft": [
        "What"
      ],
      "supporting_unit_ids": [
        "u-L0045-03"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "What now?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_04",
      "category": "entity_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Sure they were heroes of Stone Bridge, and definitely the saviors of Bubbles the Float Goat, but so what?",
      "must_hit_tokens_draft": [
        "Sure",
        "Stone Bridge",
        "Bubbles",
        "Float Goat"
      ],
      "supporting_unit_ids": [
        "u-L0045-04"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "Sure they were heroes of Stone Bridge, and definitely the saviors of Bubbles the Float Goat, but so what?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_05",
      "category": "consequence_or_hook_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "What about that city Pippa was talking about, where they were having a festival?",
      "must_hit_tokens_draft": [
        "What",
        "Pippa"
      ],
      "supporting_unit_ids": [
        "u-L0045-05"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "What about that city Pippa was talking about, where they were having a festival?"
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_06",
      "category": "consequence_or_hook_context",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Mirathorn, that might be interesting... Long way on foot, but not that far.",
      "must_hit_tokens_draft": [
        "Mirathorn",
        "Long"
      ],
      "supporting_unit_ids": [
        "u-L0045-06"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "Mirathorn, that might be interesting... Long way on foot, but not that far."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_07",
      "category": "core_recall",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Maybe a bit more than a week.",
      "must_hit_tokens_draft": [
        "Maybe"
      ],
      "supporting_unit_ids": [
        "u-L0045-07"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "Maybe a bit more than a week."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    },
    {
      "candidate_id": "c1s3_cand_u_L0045_08",
      "category": "core_recall",
      "question": "What should I remember from this Session 3 beat for next prep?",
      "expected_answer_draft": "Not much to do around Stone Bridge unless you are into rebuilding and staying still.",
      "must_hit_tokens_draft": [
        "Not",
        "Stone Bridge"
      ],
      "supporting_unit_ids": [
        "u-L0045-08"
      ],
      "supporting_route_substrings": [],
      "supporting_evidence_snippets": [
        "Not much to do around Stone Bridge unless you are into rebuilding and staying still."
      ],
      "notes": "Draft from deterministic unit walk; human should rewrite question into natural GM phrasing.",
      "review_status": "pending"
    }
  ]
} as const;
// END GENERATED C1S3_CANDIDATE_DETAIL

function CandidateCard({ row }: { row: CandidateRow }) {
  return (
    <Card key={row.candidate_id}>
      <CardHeader>
        <Stack gap={6}>
          <Text size="large" weight="semibold">
            {row.candidate_id}
          </Text>
          <Stack direction="horizontal" gap={6}>
            <Pill tone="info">{row.category}</Pill>
            <Pill tone={row.review_status === 'accept' ? 'success' : 'neutral'}>{row.review_status}</Pill>
          </Stack>
        </Stack>
      </CardHeader>
      <CardBody>
        <Stack gap={8}>
          <Text weight="semibold">Draft question</Text>
          <Text tone="secondary">{row.question}</Text>
          <Text weight="semibold">Expected answer (draft)</Text>
          <Text tone="secondary">{row.expected_answer_draft}</Text>
          <Text weight="semibold">Must-hit tokens (draft)</Text>
          <Text tone="secondary">{row.must_hit_tokens_draft.join(', ') || '—'}</Text>
          <Text weight="semibold">Routes (draft needles)</Text>
          <Text tone="secondary">
            {row.supporting_route_substrings.join(' · ') || '—'}
          </Text>
          <Text weight="semibold">Evidence snippet</Text>
          <Text tone="secondary">{row.supporting_evidence_snippets[0] ?? '—'}</Text>
          <Text size="small" tone="secondary">
            {row.notes}
          </Text>
        </Stack>
      </CardBody>
    </Card>
  );
}

export default function C1S3BreadcrumbQueryCandidateReviewCanvas() {
  const summary = c1s3CandidateCanvasGenerated.c1s3CandidateSummaryGenerated;
  const rows = c1s3CandidateCanvasGenerated.c1s3CandidateRowsGenerated as unknown as readonly CandidateRow[];
  const hasRows = rows.length > 0;

  return (
    <Stack gap={16} padding={16}>
      <H1>C1S3 — Breadcrumb query candidates</H1>
      <Text tone="secondary">
        Component-shaped review surface: one card per generated candidate. Promote accepted rows into{' '}
        <Code>gold/breadcrumb_query_natural_c1s3_v1.json</Code> after rewriting questions into natural GM phrasing.
      </Text>
      <Stack gap={4}>
        <Text>
          <strong>Source recap:</strong> <Code>{sourceRecap}</Code>
        </Text>
        <Text>
          <strong>Breadcrumb index:</strong> <Code>{breadcrumbArtifact}</Code>
        </Text>
        <Text>
          <strong>Candidate artifact:</strong> <Code>{candidateArtifact}</Code>
        </Text>
      </Stack>
      <Callout tone="info" title="Regenerate">
        <Text>
          <Code>uv run python -m evals.sentence_routing_retrieval_falsification.c1s3_query_candidate_build</Code>
          <br />
          <Code>uv run python -m evals.sentence_routing_retrieval_falsification.c1s3_query_candidate_canvas_emit --candidates {candidateArtifact} --canvas-tsx ~/.cursor/projects/.../canvases/c1s3-breadcrumb-query-candidate-review.canvas.tsx</Code>
        </Text>
      </Callout>
      <Divider />
      {hasRows ? (
        <>
          <H2>
            Candidates ({summary.candidate_count}) — session {summary.session_number}
          </H2>
          <Stack gap={10}>
            {rows.map((row) => (
              <CandidateCard key={row.candidate_id} row={row} />
            ))}
          </Stack>
        </>
      ) : (
        <Callout tone="warning" title="Generated block is empty">
          <Text>Run the candidate builder + emitter (see above).</Text>
        </Callout>
      )}
    </Stack>
  );
}
