import { describe, expect, it } from "vitest";
import type { GoldReviewCompareResponse, ManualReviewBedDetail, ManualReviewVariantDetail } from "../../api/types";
import { buildVariantLiveInventoryIndex, manualVariantToLaneView, normalizeInventoryLabel } from "./graphReviewVariantReferenceUtils";

function variant(overrides: Partial<ManualReviewVariantDetail> = {}): ManualReviewVariantDetail {
  return { variant_name: "v1", node_count: 1, edge_count: 1, cost_usd: 0.1, nodes: [{ node_id: "n1", label: "Lysandra", node_type: "actor", evidence_span_ids: ["s1"], anchor_quotes: ["quote"] }], edges: [{ edge_id: "e1", from_node_id: "n1", to_node_id: "n2", relationship_type: "Protects", evidence_span_ids: ["s2"], anchor_quotes: ["edge quote"] }], node_kinds: { actor: 1 }, edge_predicates: { Protects: 1 }, gold_comparison: {}, party_context: {}, ...overrides };
}
function bed(): ManualReviewBedDetail { return { schema_version: "dmb_graph_manual_review_bed_v1", version: "1", bed_id: "bed1", campaign_id: "c1", session_id: "s1", generated_at: "now", model_id: "model", node_prompt_contexts: {}, edge_prompt_context: "", variant_names: ["v1"], variants: { v1: variant() } }; }
function compare(live: GoldReviewCompareResponse["object_index"]["live"]): GoldReviewCompareResponse { return { schema_version: "dmb_graph_gold_review_compare_v1", version: "1", session_id: "s1", campaign_id: "c1", gold_fixture_id: "g", gold_manifest_path: "g", gold_graph_path: "g", live_run: null, comparison: { scores: {}, coverage: {}, soft_misses: [] }, object_index: { gold: {}, live }, match_pairs: {} }; }

describe("graphReviewVariantReferenceUtils", () => {
  it("normalizes labels case, spacing, and surrounding punctuation", () => expect(normalizeInventoryLabel("  !! Lysandra   Ironveil, ")).toBe("lysandra ironveil"));
  it("builds lane view for existing variant", () => expect(manualVariantToLaneView({ bed: bed(), variantName: "v1" })?.lane.sourceKind).toBe("manual_review_variant"));
  it("returns null for missing variant", () => expect(manualVariantToLaneView({ bed: bed(), variantName: "missing" })).toBeNull());
  it("empty variant returns empty index with warning", () => expect(buildVariantLiveInventoryIndex({ variant: null, compare: null }).warnings.length).toBeGreaterThan(0));
  it("no compare returns variant-only rows and warning", () => { const index = buildVariantLiveInventoryIndex({ variant: variant(), compare: null }); expect(index.countsByStatus.variant_only).toBe(2); expect(index.warnings[0]).toContain("unavailable"); });
  it("variant node with same live node label becomes kind_label_overlap", () => expect(buildVariantLiveInventoryIndex({ variant: variant({ edges: [], edge_count: 0 }), compare: compare({ l1: { object_kind: "nodes", object_id: "l1", label: "Lysandra", payload: {} } }) }).rows[0].status).toBe("kind_label_overlap"));
  it("variant edge with same live edge label becomes kind_label_overlap", () => expect(buildVariantLiveInventoryIndex({ variant: variant({ nodes: [], node_count: 0 }), compare: compare({ l1: { object_kind: "edges", object_id: "l1", label: "Protects", payload: {} } }) }).rows[0].status).toBe("kind_label_overlap"));
  it("variant node with same live edge label becomes label_overlap", () => expect(buildVariantLiveInventoryIndex({ variant: variant({ nodes: [{ node_id: "n1", label: "Protects", node_type: "concept", evidence_span_ids: [], anchor_quotes: [] }], edges: [], edge_count: 0 }), compare: compare({ l1: { object_kind: "edges", object_id: "l1", label: "Protects", payload: {} } }) }).rows[0].status).toBe("label_overlap"));
  it("emits variant-only and live-only rows", () => { const index = buildVariantLiveInventoryIndex({ variant: variant({ edges: [], edge_count: 0 }), compare: compare({ l1: { object_kind: "nodes", object_id: "l1", label: "Other", payload: {} } }) }); expect(index.countsByStatus.variant_only).toBe(1); expect(index.countsByStatus.live_only).toBe(1); });
  it("duplicate variant labels become comparator_uncertain", () => expect(buildVariantLiveInventoryIndex({ variant: variant({ nodes: [{ node_id: "n1", label: "A", node_type: "actor", evidence_span_ids: [], anchor_quotes: [] }, { node_id: "n2", label: "A", node_type: "actor", evidence_span_ids: [], anchor_quotes: [] }], edges: [], edge_count: 0 }), compare: compare({}) }).countsByStatus.comparator_uncertain).toBe(2));
  it("duplicate live labels become comparator_uncertain", () => expect(buildVariantLiveInventoryIndex({ variant: variant({ nodes: [{ node_id: "n1", label: "A", node_type: "actor", evidence_span_ids: [], anchor_quotes: [] }], edges: [], edge_count: 0 }), compare: compare({ l1: { object_kind: "nodes", object_id: "l1", label: "A", payload: {} }, l2: { object_kind: "nodes", object_id: "l2", label: "A", payload: {} } }) }).countsByStatus.comparator_uncertain).toBe(1));
  it("counts initialize all statuses", () => expect(Object.keys(buildVariantLiveInventoryIndex({ variant: null, compare: null }).countsByStatus).sort()).toEqual(["comparator_uncertain", "kind_label_overlap", "label_overlap", "live_only", "variant_only"].sort()));
  it("sorts rows deterministically by status priority and label", () => { const index = buildVariantLiveInventoryIndex({ variant: variant({ nodes: [{ node_id: "n1", label: "B", node_type: "actor", evidence_span_ids: [], anchor_quotes: [] }, { node_id: "n2", label: "A", node_type: "actor", evidence_span_ids: [], anchor_quotes: [] }], edges: [], edge_count: 0 }), compare: compare({}) }); expect(index.rows.map((row) => row.label)).toEqual(["A", "B"]); });
});
